// Unsplash URLs for real flower images - stable and high quality
const FLOWER_IMAGES: Record<string, string> = {
  'hoa-lan-soc': 'https://images.unsplash.com/photo-1566936739037-e9a4f0a3a19c?w=800&h=800&fit=crop',
  'hoa-bach-hop': 'https://images.unsplash.com/photo-1468327768560-75b778cbb551?w=800&h=800&fit=crop',
  'hoa-lan-vanda': 'https://images.unsplash.com/photo-1566936739037-e9a4f0a3a19c?w=800&h=800&fit=crop',
  'hoa-lan-cat': 'https://images.unsplash.com/photo-1541697418506-f1ee9d59db21?w=800&h=800&fit=crop',
  'hoa-lan-mokara': 'https://images.unsplash.com/photo-1566936739037-e9a4f0a3a19c?w=800&h=800&fit=crop',
  'hoa-lan-oncidium': 'https://images.unsplash.com/photo-1541697418506-f1ee9d59db21?w=800&h=800&fit=crop',
  'hoa-lan-cymbidium': 'https://images.unsplash.com/photo-1566936739037-e9a4f0a3a19c?w=800&h=800&fit=crop',
  'hoa-iris': 'https://images.unsplash.com/photo-1457089328109-e5d9bd499191?w=800&h=800&fit=crop',
  'hoa-gladiolus': 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&h=800&fit=crop',
  'hoa-tuberose': 'https://images.unsplash.com/photo-1588779844229-9e6f0e5c5f1a?w=800&h=800&fit=crop',
  'hoa-night-jasmine': 'https://images.unsplash.com/photo-1587814213271-7a6625b76c33?w=800&h=800&fit=crop',
  'hoa-queen-of-night': 'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=800&h=800&fit=crop',
  'hoa-moonflower': 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&h=800&fit=crop',
  'hoa-angel-trumpet': 'https://images.unsplash.com/photo-1519378058457-4c29a0a2efac?w=800&h=800&fit=crop',
  'hoa-four-oclock': 'https://images.unsplash.com/photo-1518882605630-8eb392ed3632?w=800&h=800&fit=crop',
  'hoa-evening-primrose': 'https://images.unsplash.com/photo-1508619870634-e55696632d12?w=800&h=800&fit=crop',
  'hoa-night-blooming-cereus': 'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=800&h=800&fit=crop',
  'hoa-crinum': 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&h=800&fit=crop',
  'hoa-hippeastrum': 'https://images.unsplash.com/photo-1518882605630-8eb392ed3632?w=800&h=800&fit=crop',
  'hoa-agave': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop',
  'hoa-bird-paradise-white': 'https://images.unsplash.com/photo-1530575832922-40799e16a02e?w=800&h=800&fit=crop',
  'hoa-torch-ginger': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop',
  'hoa-costus': 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&h=800&fit=crop',
  'hoa-porcelain-flower': 'https://images.unsplash.com/photo-1519378058457-4c29a0a2efac?w=800&h=800&fit=crop',
  'hoa-jade-vine': 'https://images.unsplash.com/photo-1597826368522-9f4cb5a6ba48?w=800&h=800&fit=crop',
  'hoa-ylang-ylang': 'https://images.unsplash.com/photo-1508619870634-e55696632d12?w=800&h=800&fit=crop',
  'hoa-champak': 'https://images.unsplash.com/photo-1589994160839-163cd867cfe8?w=800&h=800&fit=crop',
  'hoa-kaffir-lily': 'https://images.unsplash.com/photo-1518882605630-8eb392ed3632?w=800&h=800&fit=crop',
};

const img = (_id: string, slug: string, primary = true) => ({
  url: FLOWER_IMAGES[slug] ?? 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&h=800&fit=crop',
  publicId: `flowery/flowers/${slug}`,
  isPrimary: primary,
});
const care = (vi: string, en: string) => ({ vi, en });
const cultural = (vi: string, en: string) => ({ vi, en });

export const flowersBatch4 = [
  {
    name: { vi: 'Hoa Lan Sóc', en: 'Dendrobium Nobile Orchid' },
    scientificName: 'Dendrobium nobile',
    slug: 'hoa-lan-soc',
    description: {
      vi: 'Lan Sóc là giống lan rừng phổ biến ở Việt Nam, có hoa mọc thành chùm dọc thân. Hoa có hương thơm nhẹ, nhiều màu sắc từ trắng đến tím.',
      en: 'Dendrobium nobile is a popular forest orchid in Vietnam, with flowers growing in clusters along the stem. The blooms have a light fragrance and range from white to purple.',
    },
    meanings: ['thanh nhã', 'quý phái', 'kiên cường', 'vẻ đẹp tự nhiên'],
    colors: ['trắng', 'tím', 'hồng'],
    seasons: ['spring', 'winter'],
    images: [img('1582794543139-8ac70d8d2e98', 'hoa-lan-soc')],
    careInstructions: care(
      'Trồng nơi có ánh sáng lọc, tưới khi giá thể khô. Cần giai đoạn lạnh để kích thích ra hoa.',
      'Grow in filtered light, water when medium is dry. Requires a cool period to trigger blooming.',
    ),
    culturalSignificance: cultural(
      'Lan Sóc được săn lùng trong giới chơi lan Việt Nam. Là biểu tượng của vẻ đẹp hoang dã và sự kiên cường.',
      'Dendrobium nobile is highly sought after among Vietnamese orchid enthusiasts. It symbolizes wild beauty and resilience.',
    ),
    popularityScore: 48,
  },
  {
    name: { vi: 'Hoa Bách Hợp', en: 'Asiatic Lily' },
    scientificName: 'Lilium asiaticum',
    slug: 'hoa-bach-hop',
    description: {
      vi: 'Hoa Bách Hợp là loài hoa loa kèn Á Đông với cánh hoa rộng, màu sắc rực rỡ từ hồng đến cam và đỏ. Loài hoa này được yêu thích vì vẻ đẹp tươi tắn và dễ trồng trong điều kiện Việt Nam.',
      en: 'The Asiatic Lily is a stunning East Asian lily with broad petals in vibrant shades of pink, orange, and red. This flower is loved for its fresh beauty and ease of cultivation in Vietnamese conditions.',
    },
    meanings: ['thuần khiết', 'thịnh vượng', 'tình yêu', 'may mắn'],
    colors: ['hồng', 'cam', 'vàng', 'đỏ'],
    seasons: ['summer'],
    images: [img('1508193638397-1cc4ff75b843', 'hoa-bach-hop')],
    careInstructions: care(
      'Trồng ở nơi có ánh nắng đầy đủ, đất thoát nước tốt. Tưới đều đặn và bón phân mỗi tháng một lần.',
      'Plant in full sun with well-draining soil. Water regularly and fertilize once a month.',
    ),
    culturalSignificance: cultural(
      'Hoa Bách Hợp tượng trưng cho sự thuần khiết và trăm năm hạnh phúc trong văn hóa Á Đông. Thường xuất hiện trong các dịp cưới hỏi và lễ mừng thọ.',
      'The Asiatic Lily symbolizes purity and a hundred years of happiness in East Asian culture. It is commonly used in weddings and longevity celebrations.',
    ),
    popularityScore: 52,
  },
  {
    name: { vi: 'Hoa Hồng Nhật', en: 'Japanese Rose' },
    scientificName: 'Rosa rugosa',
    slug: 'hoa-hong-nhat',
    description: {
      vi: 'Hoa Hồng Nhật là giống hồng dại có nguồn gốc từ Nhật Bản và Đông Á, nổi tiếng với hương thơm nồng và cánh hoa dày. Cây có sức sống mạnh mẽ và chịu đựng được điều kiện khắc nghiệt.',
      en: 'The Japanese Rose is a wild rose native to Japan and East Asia, renowned for its intense fragrance and thick petals. The plant is vigorous and tolerates harsh conditions well.',
    },
    meanings: ['tình yêu bền chặt', 'sức sống', 'vẻ đẹp giản dị', 'kiên nhẫn'],
    colors: ['hồng', 'đỏ'],
    seasons: ['spring', 'summer'],
    images: [img('1518531933037-91b2f5f229cc', 'hoa-hong-nhat')],
    careInstructions: care(
      'Trồng nơi có ánh sáng mặt trời đầy đủ, đất pha cát thoát nước. Cắt tỉa sau mỗi vụ hoa để cây phát triển tốt hơn.',
      'Plant in full sun with sandy, well-drained soil. Prune after each flowering season for better growth.',
    ),
    culturalSignificance: cultural(
      'Hoa Hồng Nhật được trân trọng trong văn hóa Nhật Bản như biểu tượng của tình yêu bền vững và vẻ đẹp tự nhiên. Ở Việt Nam, loài hoa này thường được dùng để pha trà thảo dược.',
      'The Japanese Rose is treasured in Japanese culture as a symbol of enduring love and natural beauty. In Vietnam, this flower is often used to brew herbal tea.',
    ),
    popularityScore: 38,
  },
  {
    name: { vi: 'Hoa Cỏ Bốn Lá', en: 'Four-leaf Clover' },
    scientificName: 'Trifolium repens',
    slug: 'hoa-co-bon-la',
    description: {
      vi: 'Hoa Cỏ Bốn Lá là loài cỏ thảo mộc nổi tiếng với những chiếc lá bốn cánh mang lại may mắn, hoa nhỏ màu trắng mọc thành cụm. Đây là loài thực vật thấp, lan rộng và phổ biến ở các bãi cỏ.',
      en: 'The Four-leaf Clover is a herbaceous plant famous for its lucky four-leafed specimens, bearing small white flowers in clusters. It is a low-growing, spreading plant common in grasslands.',
    },
    meanings: ['may mắn', 'hy vọng', 'tình yêu', 'đức tin'],
    colors: ['xanh lá', 'trắng'],
    seasons: ['spring'],
    images: [img('1558618666-fcd25c85cd64', 'hoa-co-bon-la')],
    careInstructions: care(
      'Trồng ở đất ẩm, thoáng, có ánh sáng vừa phải. Không cần chăm sóc nhiều, cỏ bốn lá tự lan rộng theo thời gian.',
      'Grow in moist, airy soil with moderate light. Requires little care as clover naturally spreads over time.',
    ),
    culturalSignificance: cultural(
      'Cỏ bốn lá từ lâu đã là biểu tượng của may mắn trong văn hóa phương Tây và được yêu thích ở Việt Nam. Tìm thấy một chiếc lá bốn cánh được xem là điềm may hiếm có.',
      'Four-leaf clover has long been a symbol of good luck in Western culture and is beloved in Vietnam. Finding a four-leafed specimen is considered a rare and fortunate omen.',
    ),
    popularityScore: 25,
  },
  {
    name: { vi: 'Hoa Trinh Nữ', en: 'Sensitive Plant' },
    scientificName: 'Mimosa pudica',
    slug: 'hoa-trinh-nu',
    description: {
      vi: 'Hoa Trinh Nữ là loài cây độc đáo với lá có khả năng cụp lại khi bị chạm vào, hoa màu hồng tím mọc thành cụm tròn. Cây thường được trồng làm cảnh vì tính thú vị và hoa đẹp.',
      en: 'The Sensitive Plant is a unique species with leaves that fold inward when touched, bearing pink-purple flowers in round clusters. It is commonly grown as an ornamental plant for its fascinating behavior and pretty blooms.',
    },
    meanings: ['nhạy cảm', 'khiêm tốn', 'e thẹn', 'tự bảo vệ'],
    colors: ['hồng', 'tím'],
    seasons: ['all_year'],
    images: [img('1597848212624-a19eb35e2651', 'hoa-trinh-nu')],
    careInstructions: care(
      'Trồng nơi có ánh nắng đầy đủ, đất thoát nước tốt. Tưới vừa phải, tránh để đất quá ẩm.',
      'Plant in full sun with well-drained soil. Water moderately, avoiding waterlogged conditions.',
    ),
    culturalSignificance: cultural(
      'Hoa Trinh Nữ tượng trưng cho sự nhạy cảm và khiêm tốn trong văn hóa Việt Nam. Cây thường được trồng trong vườn nhà để dạy trẻ em về sự nhạy cảm của thiên nhiên.',
      'The Sensitive Plant symbolizes sensitivity and humility in Vietnamese culture. It is often grown in home gardens to teach children about the responsiveness of nature.',
    ),
    popularityScore: 20,
  },
  {
    name: { vi: 'Hoa Quỳnh Anh', en: 'Double Cherry Blossom' },
    scientificName: 'Prunus serrulata',
    slug: 'hoa-quynh-anh',
    description: {
      vi: 'Hoa Quỳnh Anh là giống anh đào Nhật Bản với những bông hoa kép dày cánh, màu hồng nhạt mềm mại. Mỗi mùa xuân, cây nở rộ tạo nên cảnh sắc tuyệt đẹp như mưa hoa hồng.',
      en: 'Double Cherry Blossom is a Japanese cherry cultivar with densely double flowers in soft pale pink. Each spring, the tree blooms spectacularly, creating a scene like a rain of pink petals.',
    },
    meanings: ['vẻ đẹp thoáng qua', 'tình yêu', 'mùa xuân', 'sự tái sinh'],
    colors: ['hồng nhạt', 'hồng'],
    seasons: ['spring'],
    images: [img('1522383225745-53eb9ee9ef27', 'hoa-quynh-anh')],
    careInstructions: care(
      'Trồng nơi có ánh sáng đầy đủ, đất tơi xốp và thoát nước. Tưới đều đặn vào mùa khô, cắt tỉa sau khi hoa tàn.',
      'Plant in full light with loose, well-drained soil. Water regularly during dry seasons and prune after flowering.',
    ),
    culturalSignificance: cultural(
      'Hoa anh đào kép gắn liền với lễ hội Hanami của Nhật Bản và ngày càng được yêu thích tại Việt Nam. Hoa tượng trưng cho vẻ đẹp ngắn ngủi nhưng đáng trân trọng của cuộc sống.',
      'Double cherry blossom is linked to Japan\'s Hanami festival and has become increasingly beloved in Vietnam. The flower symbolizes the fleeting yet precious beauty of life.',
    ),
    popularityScore: 42,
  },
  {
    name: { vi: 'Hoa Thạch Lựu', en: 'Pomegranate Blossom' },
    scientificName: 'Punica granatum',
    slug: 'hoa-thach-luu',
    description: {
      vi: 'Hoa Thạch Lựu có màu đỏ cam rực rỡ, cánh hoa mỏng manh nhưng cây lại rất sai quả. Hoa nở vào mùa hè báo hiệu mùa lựu chín, mang theo hương thơm ngọt ngào.',
      en: 'Pomegranate Blossom is brilliant red-orange with delicate petals, yet the tree is very fruitful. The flowers bloom in summer heralding the pomegranate harvest, carrying a sweet fragrance.',
    },
    meanings: ['sinh sôi', 'thịnh vượng', 'may mắn', 'tình yêu đôi lứa'],
    colors: ['đỏ', 'cam'],
    seasons: ['summer'],
    images: [img('1601004890843-c1f4f3e8af61', 'hoa-thach-luu')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, tưới vừa phải và bón phân hữu cơ định kỳ. Cây chịu hạn tốt nhưng cần tưới đều để ra hoa nhiều.',
      'Plant in full sun, water moderately and apply organic fertilizer periodically. The plant tolerates drought but needs regular watering for abundant blooms.',
    ),
    culturalSignificance: cultural(
      'Hoa và quả thạch lựu là biểu tượng của sự sinh sôi và may mắn trong nhiều nền văn hóa Á Đông. Ở Việt Nam, cây thạch lựu thường được trồng trước nhà để cầu phúc.',
      'Pomegranate flowers and fruit symbolize fertility and good fortune in many East Asian cultures. In Vietnam, pomegranate trees are often planted in front of homes to invite blessings.',
    ),
    popularityScore: 30,
  },
  {
    name: { vi: 'Hoa Súng Đỏ', en: 'Red Water Lily' },
    scientificName: 'Nymphaea rubra',
    slug: 'hoa-sung-do',
    description: {
      vi: 'Hoa Súng Đỏ là loài thủy sinh nổi tiếng với những bông hoa đỏ thắm nổi trên mặt nước. Hoa nở ban ngày và khép lại vào chiều tối, tạo nên vẻ đẹp huyền bí trên ao hồ.',
      en: 'The Red Water Lily is an aquatic plant renowned for its deep red flowers floating on the water surface. The blooms open during the day and close at dusk, creating a mysterious beauty on ponds and lakes.',
    },
    meanings: ['nhiệt huyết', 'tình yêu nồng cháy', 'sức sống', 'vẻ đẹp thuần khiết'],
    colors: ['đỏ', 'hồng'],
    seasons: ['summer'],
    images: [img('1519619091416-f5bc0ad1e71d', 'hoa-sung-do')],
    careInstructions: care(
      'Trồng trong chậu đất và đặt trong hồ nước, mực nước khoảng 30-60cm. Cần nhiều ánh nắng, ít nhất 6 giờ mỗi ngày.',
      'Plant in clay pots placed in a pond with 30-60cm of water depth. Requires plenty of sunlight, at least 6 hours per day.',
    ),
    culturalSignificance: cultural(
      'Hoa súng đỏ gắn liền với hình ảnh đồng quê Việt Nam và ao làng thanh bình. Là biểu tượng của sức sống mãnh liệt và vẻ đẹp thuần túy của thiên nhiên.',
      'The Red Water Lily is associated with the image of Vietnamese countryside and peaceful village ponds. It is a symbol of vibrant life and the pure beauty of nature.',
    ),
    popularityScore: 35,
  },
  {
    name: { vi: 'Hoa Nữ Hoàng Xanh', en: 'Eryngium' },
    scientificName: 'Eryngium planum',
    slug: 'hoa-nu-hoang-xanh',
    description: {
      vi: 'Hoa Nữ Hoàng Xanh là loài hoa độc đáo với màu xanh thép đặc trưng, cánh hoa cứng và có gai như xương rồng. Hoa thường được sử dụng trong cắm hoa nghệ thuật để tạo điểm nhấn đặc biệt.',
      en: 'Eryngium is a unique flower with its distinctive steel-blue color and stiff, spiny bracts resembling cactus spines. It is frequently used in floral arrangements to create a striking visual accent.',
    },
    meanings: ['độc lập', 'mạnh mẽ', 'sự khác biệt', 'bí ẩn'],
    colors: ['xanh'],
    seasons: ['summer', 'autumn'],
    images: [img('1597848212624-a19eb35e2651', 'hoa-nu-hoang-xanh')],
    careInstructions: care(
      'Trồng nơi có đủ nắng, đất khô và thoát nước tốt. Cây chịu hạn tốt, không cần tưới nhiều.',
      'Plant in full sun with dry, well-drained soil. The plant is drought-tolerant and does not need frequent watering.',
    ),
    culturalSignificance: cultural(
      'Eryngium ngày càng được ưa chuộng trong nghệ thuật cắm hoa hiện đại tại Việt Nam. Màu xanh độc đáo của hoa tạo sự tương phản đẹp trong các bó hoa và tác phẩm nghệ thuật.',
      'Eryngium is increasingly favored in modern floral art in Vietnam. The flower\'s unique blue color creates a beautiful contrast in bouquets and artistic arrangements.',
    ),
    popularityScore: 32,
  },
  {
    name: { vi: 'Hoa Lan Hài', en: 'Slipper Orchid' },
    scientificName: 'Paphiopedilum',
    slug: 'hoa-lan-hai',
    description: {
      vi: 'Hoa Lan Hài nổi tiếng với cánh hoa hình chiếc dép độc đáo, màu sắc pha trộn tinh tế giữa nâu, vàng và xanh. Đây là một trong những loài lan quý hiếm nhất và được bảo vệ nghiêm ngặt tại Việt Nam.',
      en: 'Slipper Orchid is famous for its unique slipper-shaped pouch, with colors delicately blending brown, yellow, and green. It is one of the rarest and most strictly protected orchid species in Vietnam.',
    },
    meanings: ['quý phái', 'hiếm có', 'hoàn hảo', 'sang trọng'],
    colors: ['nâu', 'vàng', 'xanh lá'],
    seasons: ['spring', 'winter'],
    images: [img('1587131782564-fe45de7c0c11', 'hoa-lan-hai')],
    careInstructions: care(
      'Trồng trong giá thể thoáng khí như vỏ dừa, đặt nơi ánh sáng lọc. Tưới khi giá thể gần khô và duy trì độ ẩm không khí cao.',
      'Grow in airy medium such as coconut husk, placed in filtered light. Water when the medium is nearly dry and maintain high air humidity.',
    ),
    culturalSignificance: cultural(
      'Lan Hài là loài lan quý được liệt vào sách đỏ và được bảo tồn chặt chẽ. Trong giới chơi lan, sở hữu một cây Lan Hài là niềm tự hào và biểu tượng của sự am hiểu nghệ thuật.',
      'Slipper Orchid is a precious species listed in the Red Book and strictly conserved. Among orchid enthusiasts, owning a Slipper Orchid is a source of pride and a symbol of connoisseurship.',
    ),
    popularityScore: 55,
  },
  {
    name: { vi: 'Hoa Cúc Đà Lạt', en: 'Da Lat Chrysanthemum' },
    scientificName: "Chrysanthemum 'Da Lat'",
    slug: 'hoa-cuc-da-lat',
    description: {
      vi: 'Hoa Cúc Đà Lạt là niềm tự hào của thành phố hoa Đà Lạt, nổi tiếng với màu sắc tươi sáng và độ bền lâu. Được trồng quanh năm trong điều kiện khí hậu lý tưởng của Đà Lạt, hoa cúc nơi đây có chất lượng tốt nhất cả nước.',
      en: 'Da Lat Chrysanthemum is the pride of Da Lat flower city, famous for its bright colors and long-lasting blooms. Grown year-round in Da Lat\'s ideal climate, these chrysanthemums are the finest quality in the country.',
    },
    meanings: ['trường thọ', 'may mắn', 'niềm vui', 'sự thuần khiết'],
    colors: ['vàng', 'trắng', 'hồng', 'tím'],
    seasons: ['all_year'],
    images: [img('1508610048994-10b5f15441b4', 'hoa-cuc-da-lat')],
    careInstructions: care(
      'Trồng nơi có nắng vừa phải, đất giàu dinh dưỡng và thoát nước. Tưới đều đặn sáng và chiều, bón phân hữu cơ mỗi hai tuần.',
      'Plant in moderate sun with nutrient-rich, well-drained soil. Water regularly morning and evening, apply organic fertilizer every two weeks.',
    ),
    culturalSignificance: cultural(
      'Hoa cúc Đà Lạt là sản phẩm thương hiệu của cao nguyên Lâm Đồng, được xuất khẩu đi nhiều nước. Hoa cúc là biểu tượng của sự trường thọ và thường xuất hiện trong các dịp lễ tết quan trọng.',
      'Da Lat chrysanthemums are a branded product of the Lam Dong Plateau, exported to many countries. Chrysanthemums symbolize longevity and are often featured in important festivals and Tet celebrations.',
    ),
    popularityScore: 62,
  },
  {
    name: { vi: 'Hoa Tiger Lily', en: 'Tiger Lily' },
    scientificName: 'Lilium lancifolium',
    slug: 'hoa-tiger-lily',
    description: {
      vi: 'Hoa Tiger Lily nổi bật với những cánh hoa cam rực rỡ điểm đốm đen như da hổ. Đây là loài hoa hoang dã mạnh mẽ, thường mọc ven đường và sườn đồi, mang vẻ đẹp tự nhiên phóng khoáng.',
      en: 'Tiger Lily stands out with its brilliant orange petals spotted with black markings resembling a tiger\'s skin. It is a robust wild flower often found along roadsides and hillsides, carrying a free-spirited natural beauty.',
    },
    meanings: ['dũng cảm', 'tự hào', 'đam mê', 'sức mạnh'],
    colors: ['cam', 'đỏ'],
    seasons: ['summer'],
    images: [img('1559181567-c3190baa3e5a', 'hoa-tiger-lily')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ hoặc nửa nắng, đất thoát nước. Tưới đều mùa sinh trưởng, giảm tưới sau khi hoa tàn.',
      'Plant in full sun or partial shade with well-drained soil. Water regularly during the growing season and reduce watering after blooming.',
    ),
    culturalSignificance: cultural(
      'Tiger Lily được biết đến là biểu tượng của sự tự hào và dũng cảm trong nhiều nền văn hóa. Tại Việt Nam, hoa thường được trồng trong vườn để tạo điểm nhấn màu sắc rực rỡ.',
      'Tiger Lily is known as a symbol of pride and courage in many cultures. In Vietnam, it is often planted in gardens to create a bold splash of color.',
    ),
    popularityScore: 35,
  },
  {
    name: { vi: 'Hoa Hồng Bụi', en: 'Spray Rose' },
    scientificName: "Rosa 'Spray'",
    slug: 'hoa-hong-bui',
    description: {
      vi: 'Hoa Hồng Bụi là giống hồng với nhiều nụ nhỏ mọc thành chùm trên một cành, tạo nên vẻ đẹp phong phú và lãng mạn. Loài hoa này được ưa chuộng trong ngành cắm hoa vì tính linh hoạt và màu sắc đa dạng.',
      en: 'Spray Rose is a rose variety with multiple small buds clustered on a single stem, creating a lush and romantic appearance. This flower is highly favored in floristry for its versatility and diverse color range.',
    },
    meanings: ['tình yêu nhỏ nhắn', 'lãng mạn', 'vui tươi', 'trân trọng'],
    colors: ['hồng', 'trắng', 'đỏ', 'cam'],
    seasons: ['all_year'],
    images: [img('1497436072909-60f360fb1003', 'hoa-hong-bui')],
    careInstructions: care(
      'Trồng nơi có ánh sáng đầy đủ, tưới đều và bón phân hồng định kỳ. Cắt tỉa thường xuyên để kích thích ra nhiều nụ hoa mới.',
      'Plant in full light, water regularly and apply rose fertilizer periodically. Prune frequently to encourage new bud development.',
    ),
    culturalSignificance: cultural(
      'Hoa Hồng Bụi ngày càng phổ biến trong văn hóa tặng hoa tại Việt Nam, đặc biệt dịp sinh nhật và ngày lễ tình nhân. Vẻ đẹp duyên dáng của hoa đại diện cho những tình cảm chân thành và giản dị.',
      'Spray Roses are increasingly popular in Vietnamese gifting culture, especially on birthdays and Valentine\'s Day. Their delicate beauty represents sincere and simple affection.',
    ),
    popularityScore: 58,
  },
  {
    name: { vi: 'Hoa Cúc Xanh', en: 'Blue Chrysanthemum' },
    scientificName: "Chrysanthemum 'Blue'",
    slug: 'hoa-cuc-xanh',
    description: {
      vi: 'Hoa Cúc Xanh là giống cúc đặc biệt với màu xanh tím hiếm gặp trong thế giới hoa cúc. Màu sắc độc đáo khiến loài hoa này trở thành lựa chọn nổi bật trong các bó hoa nghệ thuật và trang trí.',
      en: 'Blue Chrysanthemum is a special variety with rare blue-purple hues uncommon in the chrysanthemum world. Its unique color makes it a standout choice in artistic bouquets and decorative arrangements.',
    },
    meanings: ['bí ẩn', 'độc đáo', 'trầm lặng', 'suy tư'],
    colors: ['xanh', 'tím'],
    seasons: ['autumn'],
    images: [img('1508610048994-10b5f15441b4', 'hoa-cuc-xanh')],
    careInstructions: care(
      'Trồng nơi có ánh sáng vừa phải, tưới đều và bổ sung phân bón vi lượng. Tránh để đất quá ẩm để ngăn ngừa thối rễ.',
      'Grow in moderate light, water evenly and supplement with micronutrient fertilizer. Avoid waterlogged soil to prevent root rot.',
    ),
    culturalSignificance: cultural(
      'Hoa Cúc Xanh là sản phẩm của công nghệ nhuộm màu hoa hiện đại, thu hút sự chú ý của giới trẻ. Màu xanh độc đáo làm cho hoa trở thành món quà ấn tượng và khác biệt.',
      'Blue Chrysanthemum is a product of modern flower dyeing technology, attracting attention from younger generations. Its unique blue color makes it an impressive and distinctive gift.',
    ),
    popularityScore: 28,
  },
  {
    name: { vi: 'Hoa Hồng Cầu Vồng', en: 'Rainbow Rose' },
    scientificName: "Rosa 'Rainbow'",
    slug: 'hoa-hong-cau-vong',
    description: {
      vi: 'Hoa Hồng Cầu Vồng là tác phẩm nghệ thuật của con người, với các cánh hoa được nhuộm nhiều màu sắc rực rỡ như cầu vồng. Mỗi bông hoa là một kiệt tác màu sắc độc nhất vô nhị, biểu tượng của sự đa dạng và niềm vui.',
      en: 'The Rainbow Rose is a human artistic creation, with petals dyed in brilliant rainbow-like colors. Each bloom is a unique colorful masterpiece, symbolizing diversity and joy.',
    },
    meanings: ['đa dạng', 'niềm vui', 'sáng tạo', 'hy vọng'],
    colors: ['đỏ', 'cam', 'vàng', 'xanh', 'tím'],
    seasons: ['all_year'],
    images: [img('1518531933037-91b2f5f229cc', 'hoa-hong-cau-vong')],
    careInstructions: care(
      'Bảo quản trong bình nước sạch ở nơi thoáng mát, thay nước mỗi ngày. Tránh ánh nắng trực tiếp để giữ màu sắc lâu bền hơn.',
      'Keep in clean water in a cool, airy place, changing water daily. Avoid direct sunlight to preserve the colors longer.',
    ),
    culturalSignificance: cultural(
      'Hoa Hồng Cầu Vồng là biểu tượng của sự đa dạng và bình đẳng, được yêu thích bởi cộng đồng yêu hoa ở Việt Nam. Loài hoa này thường được tặng như món quà đặc biệt trong các dịp sinh nhật và kỷ niệm.',
      'Rainbow Rose is a symbol of diversity and equality, beloved by the flower-loving community in Vietnam. This flower is often gifted as a special present on birthdays and anniversaries.',
    ),
    popularityScore: 45,
  },
  {
    name: { vi: 'Hoa Bách Nhật', en: 'Globe Amaranth' },
    scientificName: 'Gomphrena globosa',
    slug: 'hoa-bach-nhat',
    description: {
      vi: 'Hoa Bách Nhật có những bông hoa tròn nhỏ xinh như nút áo, màu sắc rực rỡ bền màu kể cả khi đã khô. Cây nhỏ, dễ trồng và nở hoa trong thời gian dài, là lựa chọn tuyệt vời cho vườn hoa mùa hè.',
      en: 'Globe Amaranth has charming round button-like blooms in bright, fade-resistant colors even when dried. The compact plant is easy to grow and flowers for extended periods, making it an excellent choice for summer gardens.',
    },
    meanings: ['bất diệt', 'tình yêu vĩnh cửu', 'kiên trì', 'bền bỉ'],
    colors: ['hồng', 'tím', 'trắng'],
    seasons: ['summer', 'autumn'],
    images: [img('1525310072745-f49212b5ac6d', 'hoa-bach-nhat')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất thoát nước. Tưới vừa phải và ít phân bón, cây sẽ ra hoa liên tục.',
      'Plant in full sun with well-drained soil. Water moderately with minimal fertilizer for continuous blooming.',
    ),
    culturalSignificance: cultural(
      'Hoa Bách Nhật tượng trưng cho tình yêu bất diệt và sự kiên trì trong văn hóa Việt Nam. Hoa khô giữ màu sắc lâu dài nên thường được dùng trang trí và làm đồ thủ công.',
      'Globe Amaranth symbolizes undying love and perseverance in Vietnamese culture. The dried flowers retain their color for a long time and are often used for decoration and handicrafts.',
    ),
    popularityScore: 30,
  },
  {
    name: { vi: 'Hoa Song Hỷ', en: 'Double Happiness Flower' },
    scientificName: 'Catharanthus roseus',
    slug: 'hoa-song-hy',
    description: {
      vi: 'Hoa Song Hỷ là tên gọi dân gian của hoa dừa cạn, với những bông hoa nhỏ 5 cánh màu hồng hoặc đỏ thắm. Cây dễ trồng, nở hoa quanh năm và thường được dùng trang trí sân vườn và ban công.',
      en: 'Double Happiness Flower is the folk name for periwinkle, with small 5-petaled blooms in pink or deep red. The plant is easy to grow, blooms year-round and is commonly used to decorate gardens and balconies.',
    },
    meanings: ['hạnh phúc', 'may mắn đôi', 'vui vẻ', 'phồn thịnh'],
    colors: ['hồng', 'đỏ'],
    seasons: ['summer'],
    images: [img('1574684891174-df5aa67e6b2d', 'hoa-song-hy')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất thoáng và thoát nước. Tưới đều đặn nhưng không để đất quá ẩm.',
      'Plant in full sun with airy, well-drained soil. Water regularly but avoid overwatering.',
    ),
    culturalSignificance: cultural(
      'Hoa Song Hỷ mang tên gọi may mắn gắn với hôn nhân hạnh phúc trong văn hóa Á Đông. Cây thường được trồng để cầu chúc hạnh phúc đôi lứa và gia đình bình an.',
      'The Double Happiness Flower carries a lucky name associated with happy marriage in East Asian culture. The plant is often grown to wish for marital happiness and family peace.',
    ),
    popularityScore: 22,
  },
  {
    name: { vi: 'Hoa Dương Xỉ', en: 'Fern Frond' },
    scientificName: 'Matteuccia struthiopteris',
    slug: 'hoa-duong-xi',
    description: {
      vi: 'Dương Xỉ là loài thực vật cổ đại không có hoa thực sự, nhưng lá xanh mướt và cuộn tròn của nó tạo nên vẻ đẹp đặc trưng. Lá dương xỉ thường được sử dụng như phụ liệu xanh tươi trong cắm hoa nghệ thuật.',
      en: 'Fern is an ancient plant without true flowers, but its lush green fronds and distinctive curling unfurling create characteristic beauty. Fern leaves are often used as fresh green filler in artistic floral arrangements.',
    },
    meanings: ['sức sống', 'bền bỉ', 'tự nhiên', 'thư thái'],
    colors: ['xanh lá'],
    seasons: ['spring', 'summer'],
    images: [img('1558906932-4e5aeefb0f1d', 'hoa-duong-xi')],
    careInstructions: care(
      'Trồng nơi có bóng râm hoặc ánh sáng lọc, giữ đất và không khí ẩm. Tránh ánh nắng trực tiếp vì lá dễ bị cháy.',
      'Grow in shade or filtered light, keeping soil and air moist. Avoid direct sunlight as fronds are easily scorched.',
    ),
    culturalSignificance: cultural(
      'Lá dương xỉ là biểu tượng của sức sống bền bỉ qua hàng triệu năm tiến hóa. Trong nghệ thuật cắm hoa Việt Nam, lá xanh dương xỉ là phụ kiện không thể thiếu.',
      'Fern fronds symbolize resilience sustained over millions of years of evolution. In Vietnamese floral art, green fern leaves are an indispensable accessory.',
    ),
    popularityScore: 18,
  },
  {
    name: { vi: 'Hoa Kim Cúc', en: 'Golden Chrysanthemum' },
    scientificName: "Chrysanthemum 'Gold'",
    slug: 'hoa-kim-cuc',
    description: {
      vi: 'Hoa Kim Cúc là giống cúc vàng rực rỡ như vàng ròng, cánh hoa dày và tập trung thành chùm đẹp mắt. Đây là một trong những loài hoa phổ biến nhất trong dịp Tết Nguyên Đán và các lễ hội mùa thu.',
      en: 'Golden Chrysanthemum is a brilliant yellow variety as radiant as pure gold, with dense petals forming beautiful clusters. It is one of the most popular flowers during Tet New Year and autumn festivals.',
    },
    meanings: ['thịnh vượng', 'trường thọ', 'cao quý', 'niềm vui'],
    colors: ['vàng'],
    seasons: ['autumn'],
    images: [img('1508610048994-10b5f15441b4', 'hoa-kim-cuc')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, tưới vừa phải và bón phân hữu cơ mỗi tháng. Cắt tỉa đầu mùa sinh trưởng để hoa nở đều và đẹp hơn.',
      'Plant in full sun, water moderately and apply organic fertilizer monthly. Pinch back at the start of the growing season for more uniform and beautiful blooms.',
    ),
    culturalSignificance: cultural(
      'Hoa Kim Cúc là biểu tượng của sự thịnh vượng và trường thọ trong văn hóa Á Đông. Màu vàng rực rỡ mang lại may mắn và được trưng bày nhiều trong dịp Tết.',
      'Golden Chrysanthemum is a symbol of prosperity and longevity in East Asian culture. Its brilliant yellow color brings good fortune and is widely displayed during Tet.',
    ),
    popularityScore: 55,
  },
  {
    name: { vi: 'Hoa Lưỡi Hổ', en: 'Snake Plant Flower' },
    scientificName: 'Sansevieria trifasciata',
    slug: 'hoa-luoi-ho',
    description: {
      vi: 'Cây Lưỡi Hổ hiếm khi ra hoa trong điều kiện nhà ở, nhưng khi nở hoa có màu trắng nhỏ thơm ngát vào ban đêm. Đây là loài cây bền bỉ, lọc không khí tốt và thường được trồng vì lá hơn là hoa.',
      en: 'Snake Plant rarely flowers indoors, but when it does, the small white blooms are sweetly fragrant at night. It is a resilient, air-purifying plant usually grown more for its striking foliage than its flowers.',
    },
    meanings: ['bảo vệ', 'sức mạnh', 'kiên trì', 'trong lành'],
    colors: ['trắng', 'xanh lá'],
    seasons: ['all_year'],
    images: [img('1558906932-4e5aeefb0f1d', 'hoa-luoi-ho')],
    careInstructions: care(
      'Trồng nơi ít sáng, tưới rất ít và để đất khô hoàn toàn giữa các lần tưới. Đây là loài cây cực kỳ chịu hạn và khó chết.',
      'Grow in low light and water sparingly, allowing soil to dry completely between waterings. This plant is extremely drought-tolerant and very hard to kill.',
    ),
    culturalSignificance: cultural(
      'Cây Lưỡi Hổ được tin là mang lại năng lượng bảo vệ cho ngôi nhà theo phong thủy. Thường được đặt ở cửa ra vào để xua đuổi tà khí và mang lại bình an.',
      'Snake Plant is believed to bring protective energy to the home according to feng shui principles. It is often placed at entryways to ward off negative energy and bring peace.',
    ),
    popularityScore: 15,
  },
  {
    name: { vi: 'Hoa Giọt Sương', en: 'Fuchsia' },
    scientificName: 'Fuchsia hybrida',
    slug: 'hoa-giot-suong',
    description: {
      vi: 'Hoa Giọt Sương là tên gọi của hoa Fuchsia với những bông hoa rủ xuống như những giọt sương long lanh. Hoa có hai lớp cánh rực rỡ, thường kết hợp giữa hồng và tím tạo nên vẻ đẹp quyến rũ.',
      en: 'Fuchsia, known as Giọt Sương (dewdrop), has pendulous flowers that cascade like shimmering dewdrops. The blooms feature two layers of brilliant petals, often combining pink and purple for an enchanting appearance.',
    },
    meanings: ['duyên dáng', 'quyến rũ', 'thanh lịch', 'lãng mạn'],
    colors: ['hồng', 'tím', 'đỏ'],
    seasons: ['spring', 'summer'],
    images: [img('1574684891174-df5aa67e6b2d', 'hoa-giot-suong')],
    careInstructions: care(
      'Trồng nơi có bóng râm nhẹ, đất giàu dinh dưỡng và ẩm. Tưới thường xuyên và bổ sung phân bón loãng mỗi hai tuần.',
      'Plant in light shade with nutrient-rich, moist soil. Water frequently and supplement with diluted fertilizer every two weeks.',
    ),
    culturalSignificance: cultural(
      'Hoa Giọt Sương được ưa chuộng trong trang trí ban công và giỏ treo tại Việt Nam. Vẻ đẹp rủ xuống của hoa gợi lên sự duyên dáng và tinh tế trong không gian sống.',
      'Fuchsia is popular for balcony decoration and hanging baskets in Vietnam. The cascading beauty of the flowers evokes gracefulness and refinement in living spaces.',
    ),
    popularityScore: 32,
  },
  {
    name: { vi: 'Hoa Đăng Tiêu', en: 'Trumpet Vine' },
    scientificName: 'Campsis radicans',
    slug: 'hoa-dang-tieu',
    description: {
      vi: 'Hoa Đăng Tiêu là loài dây leo có hoa hình kèn trumpet màu cam đỏ rực rỡ, nở thành chùm vào mùa hè. Cây leo nhanh và có thể che phủ toàn bộ hàng rào hoặc giàn bằng màu sắc tươi sáng.',
      en: 'Trumpet Vine is a climbing plant with brilliant orange-red trumpet-shaped flowers blooming in clusters during summer. It grows quickly and can cover entire fences or trellises with its vibrant colors.',
    },
    meanings: ['nhiệt tình', 'phấn khởi', 'sức sống', 'vươn cao'],
    colors: ['cam', 'đỏ'],
    seasons: ['summer'],
    images: [img('1601004890843-c1f4f3e8af61', 'hoa-dang-tieu')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất thoát nước và có điểm tựa cho cây leo. Tưới đều mùa hè, cắt tỉa hàng năm để kiểm soát sự phát triển.',
      'Plant in full sun with well-drained soil and provide support for climbing. Water regularly in summer and prune annually to control growth.',
    ),
    culturalSignificance: cultural(
      'Hoa Đăng Tiêu thường được trồng để trang trí hàng rào và cổng nhà tại Việt Nam. Màu cam đỏ rực rỡ của hoa tạo điểm nhấn bắt mắt và thu hút chim hút mật.',
      'Trumpet Vine is commonly grown to decorate fences and house gates in Vietnam. Its brilliant orange-red flowers create striking focal points and attract nectar-feeding birds.',
    ),
    popularityScore: 25,
  },
  {
    name: { vi: 'Hoa Quế', en: 'Cinnamon Blossom' },
    scientificName: 'Cinnamomum verum',
    slug: 'hoa-que',
    description: {
      vi: 'Hoa Quế là loài hoa nhỏ của cây quế quý, màu vàng kem nhạt và tỏa hương thơm cinnamon đặc trưng. Tuy nhỏ bé nhưng hoa quế mang theo hương thơm ấm áp gợi nhớ những món ăn truyền thống.',
      en: 'Cinnamon Blossom is the small flower of the precious cinnamon tree, in pale cream yellow with a distinctive cinnamon fragrance. Though tiny, cinnamon blossoms carry a warm aroma evoking memories of traditional dishes.',
    },
    meanings: ['ấm áp', 'truyền thống', 'hương vị', 'quý giá'],
    colors: ['vàng', 'trắng'],
    seasons: ['autumn'],
    images: [img('1625231657647-9b15e0e49a0a', 'hoa-que')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất tơi xốp và thoát nước. Cây quế cần nhiều năm để trưởng thành và ra hoa.',
      'Plant in full sun with loose, well-drained soil. Cinnamon trees need many years to mature and bloom.',
    ),
    culturalSignificance: cultural(
      'Cây quế là loài cây quý trong y học cổ truyền và ẩm thực Việt Nam. Hoa quế ít được biết đến nhưng mang giá trị văn hóa và lịch sử sâu sắc.',
      'Cinnamon tree is a precious plant in Vietnamese traditional medicine and cuisine. Cinnamon blossoms are little known but carry deep cultural and historical significance.',
    ),
    popularityScore: 28,
  },
  {
    name: { vi: 'Hoa Cẩm Nhung', en: 'Velvet Celosia' },
    scientificName: 'Celosia cristata',
    slug: 'hoa-cam-nhung',
    description: {
      vi: 'Hoa Cẩm Nhung có bề mặt như nhung đỏ thắm, hình dạng độc đáo gợi lên vương miện hoặc sóng biển. Màu sắc rực rỡ và đặc biệt làm cho hoa trở thành điểm nhấn nổi bật trong bất kỳ vườn hoa nào.',
      en: 'Velvet Celosia has a velvety surface in deep red, with a unique shape evoking a crown or ocean waves. Its brilliant and distinctive colors make it a standout focal point in any flower garden.',
    },
    meanings: ['nhiệt huyết', 'đam mê', 'lòng trung thành', 'sức mạnh'],
    colors: ['đỏ', 'cam', 'vàng', 'tím'],
    seasons: ['summer', 'autumn'],
    images: [img('1525310072745-f49212b5ac6d', 'hoa-cam-nhung')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất giàu dinh dưỡng. Tưới đều đặn và bón phân hữu cơ để hoa nở to và rực rỡ hơn.',
      'Plant in full sun with nutrient-rich soil. Water regularly and apply organic fertilizer for larger and more brilliant blooms.',
    ),
    culturalSignificance: cultural(
      'Hoa Cẩm Nhung thường được trồng trong lễ hội và sự kiện đặc biệt vì màu sắc ấn tượng. Màu đỏ của hoa mang lại may mắn và thịnh vượng theo quan niệm phương Đông.',
      'Velvet Celosia is often grown for festivals and special events due to its striking colors. The red color of the flower brings good luck and prosperity according to Eastern beliefs.',
    ),
    popularityScore: 35,
  },
  {
    name: { vi: 'Hoa Thanh Liễu', en: 'Tamarisk' },
    scientificName: 'Tamarix gallica',
    slug: 'hoa-thanh-lieu',
    description: {
      vi: 'Hoa Thanh Liễu mọc thành chùm nhỏ li ti màu hồng nhạt trên những cành mảnh mai như liễu rủ. Cây tạo nên cảnh sắc nhẹ nhàng, tao nhã, thường thấy ven biển và nơi có điều kiện khô hạn.',
      en: 'Tamarisk blooms in tiny pale pink clusters on slender weeping branches. The plant creates a gentle, elegant scenery, often found along coastlines and in dry conditions.',
    },
    meanings: ['mềm mại', 'dẻo dai', 'thích nghi', 'nhẹ nhàng'],
    colors: ['hồng nhạt'],
    seasons: ['spring', 'summer'],
    images: [img('1522383225745-53eb9ee9ef27', 'hoa-thanh-lieu')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất pha cát thoát nước. Cây chịu hạn và chịu gió mặn, rất phù hợp để trồng ven biển.',
      'Plant in full sun with sandy, well-drained soil. The plant tolerates drought and salt wind, making it ideal for coastal planting.',
    ),
    culturalSignificance: cultural(
      'Cây Thanh Liễu gắn với hình ảnh vùng ven biển và những cung đường cát trắng của Việt Nam. Vẻ đẹp mảnh mai của hoa gợi lên sự duyên dáng và sức chịu đựng.',
      'Tamarisk is associated with the imagery of Vietnamese coastal areas and white sandy roads. The delicate beauty of the flowers evokes gracefulness and endurance.',
    ),
    popularityScore: 18,
  },
  {
    name: { vi: 'Hoa Bông Súng Trắng', en: 'White Water Lily' },
    scientificName: 'Nymphaea alba',
    slug: 'hoa-bong-sung-trang',
    description: {
      vi: 'Hoa Bông Súng Trắng là loài thủy sinh với những cánh hoa trắng muốt nổi trên mặt nước như những ngôi sao băng. Vẻ đẹp thanh khiết và hương thơm dịu nhẹ làm cho hoa trở thành biểu tượng của sự thuần khiết.',
      en: 'White Water Lily is an aquatic plant with pristine white petals floating on the water surface like shooting stars. Its pure beauty and subtle fragrance make it a symbol of purity and serenity.',
    },
    meanings: ['thuần khiết', 'bình yên', 'tâm linh', 'hoàn hảo'],
    colors: ['trắng'],
    seasons: ['summer'],
    images: [img('1519619091416-f5bc0ad1e71d', 'hoa-bong-sung-trang')],
    careInstructions: care(
      'Trồng trong chậu ngập nước ở ao hồ có ánh nắng đầy đủ. Bón phân viên chuyên dụng cho cây thủy sinh mỗi tháng.',
      'Plant in submerged pots in ponds with full sunlight. Apply specialized aquatic plant fertilizer pellets monthly.',
    ),
    culturalSignificance: cultural(
      'Hoa súng trắng gắn liền với hình ảnh ao sen thanh bình trong văn hóa Việt Nam. Cũng như hoa sen, hoa súng trắng tượng trưng cho sự thuần khiết và tâm hồn thanh cao.',
      'White water lily is associated with the image of peaceful lotus ponds in Vietnamese culture. Like the lotus, it symbolizes purity and a noble spirit.',
    ),
    popularityScore: 40,
  },
  {
    name: { vi: 'Hoa Nguyệt Quế', en: 'Bay Laurel' },
    scientificName: 'Laurus nobilis',
    slug: 'hoa-nguyet-que',
    description: {
      vi: 'Hoa Nguyệt Quế là những bông hoa nhỏ màu vàng kem của cây lá nguyệt quế nổi tiếng, tỏa hương thơm dịu dàng. Cây có ý nghĩa lịch sử sâu sắc và lá nguyệt quế từng được dùng làm vòng hoa vinh quang.',
      en: 'Bay Laurel produces small cream-yellow flowers on the famous laurel tree, emitting a gentle fragrance. The tree has deep historical significance and laurel leaves were once used to make victorious crowns.',
    },
    meanings: ['vinh quang', 'chiến thắng', 'trí tuệ', 'thành tựu'],
    colors: ['vàng', 'trắng'],
    seasons: ['spring'],
    images: [img('1625231657647-9b15e0e49a0a', 'hoa-nguyet-que')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ hoặc nửa nắng, đất thoát nước. Cây chịu hạn tốt và cần cắt tỉa để duy trì hình dáng.',
      'Plant in full sun or partial shade with well-drained soil. The plant is drought-tolerant and requires pruning to maintain shape.',
    ),
    culturalSignificance: cultural(
      'Vòng hoa nguyệt quế là biểu tượng của vinh quang từ thời Hy Lạp và La Mã cổ đại. Ở Việt Nam, nguyệt quế được trồng vì ý nghĩa tốt đẹp và lá được sử dụng trong nấu ăn.',
      'The laurel wreath is a symbol of glory from ancient Greece and Rome. In Vietnam, bay laurel is grown for its auspicious meaning and its leaves are used in cooking.',
    ),
    popularityScore: 22,
  },
  {
    name: { vi: 'Hoa Phong Lan Địa', en: 'Ground Orchid' },
    scientificName: 'Spathoglottis plicata',
    slug: 'hoa-phong-lan-dia',
    description: {
      vi: 'Hoa Phong Lan Địa là loài lan mọc dưới đất với hoa tím hoặc hồng thanh nhã mọc thành chùm trên thân thẳng đứng. Đây là một trong những loài lan dễ trồng nhất, phù hợp cho người mới bắt đầu chơi lan.',
      en: 'Ground Orchid is a terrestrial orchid with elegant purple or pink flowers growing in clusters on upright stems. It is one of the easiest orchids to cultivate, suitable for beginners.',
    },
    meanings: ['thanh nhã', 'duyên dáng', 'khởi đầu', 'phát triển'],
    colors: ['tím', 'hồng'],
    seasons: ['all_year'],
    images: [img('1587131782564-fe45de7c0c11', 'hoa-phong-lan-dia')],
    careInstructions: care(
      'Trồng trong đất trộn vỏ dừa và than bùn, nơi có ánh sáng vừa phải. Tưới đều đặn và bón phân lan mỗi tuần trong mùa sinh trưởng.',
      'Plant in a mix of coconut husk and peat moss in moderate light. Water regularly and apply orchid fertilizer weekly during the growing season.',
    ),
    culturalSignificance: cultural(
      'Phong Lan Địa là loài lan quen thuộc trong vườn nhà và công viên tại Việt Nam. Loài hoa này giúp nhiều người bắt đầu niềm đam mê với thế giới lan đa dạng.',
      'Ground Orchid is a familiar orchid in home gardens and parks in Vietnam. This species helps many people begin their passion for the diverse world of orchids.',
    ),
    popularityScore: 38,
  },
  {
    name: { vi: 'Hoa Cúc Vạn Thọ Pháp', en: 'French Marigold' },
    scientificName: 'Tagetes patula',
    slug: 'hoa-cuc-van-tho-phap',
    description: {
      vi: 'Hoa Cúc Vạn Thọ Pháp là giống cúc vạn thọ nhỏ nhắn với hoa màu vàng cam rực rỡ, cánh hoa kép dày dặn. Cây dễ trồng, ra hoa dày và thường được dùng để đuổi sâu bọ gây hại trong vườn.',
      en: 'French Marigold is a compact marigold variety with brilliant yellow-orange flowers and densely doubled petals. Easy to grow with abundant blooms, it is commonly used as a natural pest deterrent in gardens.',
    },
    meanings: ['may mắn', 'trường thọ', 'vui vẻ', 'sức khỏe'],
    colors: ['vàng', 'cam', 'đỏ'],
    seasons: ['summer', 'autumn'],
    images: [img('1508193638397-1cc4ff75b843', 'hoa-cuc-van-tho-phap')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất thoát nước. Tưới đều đặn và nhặt hoa tàn để kích thích nở hoa liên tục.',
      'Plant in full sun with well-drained soil. Water regularly and deadhead spent blooms to encourage continuous flowering.',
    ),
    culturalSignificance: cultural(
      'Cúc vạn thọ là loài hoa được trồng nhiều nhất trong dịp Tết Nguyên Đán để cầu chúc sức khỏe và trường thọ. Màu vàng rực của hoa tượng trưng cho sự thịnh vượng và sung túc.',
      'Marigolds are the most widely grown flowers during Tet to wish for health and longevity. The brilliant yellow color symbolizes prosperity and abundance.',
    ),
    popularityScore: 42,
  },
  {
    name: { vi: 'Hoa Bông Giấy Kép', en: 'Double Bougainvillea' },
    scientificName: "Bougainvillea 'Double'",
    slug: 'hoa-bong-giay-kep',
    description: {
      vi: 'Hoa Bông Giấy Kép là giống bougainvillea đặc biệt với lá bắc kép dày dặn, tạo ra màn hoa rực rỡ hơn giống thường. Cây leo mạnh mẽ và nở hoa quanh năm trong điều kiện nhiệt đới ẩm của Việt Nam.',
      en: 'Double Bougainvillea is a special variety with densely doubled bracts, creating a more spectacular floral display than common varieties. The vigorous climbing plant blooms year-round in Vietnam\'s tropical humid conditions.',
    },
    meanings: ['đam mê', 'nhiệt huyết', 'vượt trội', 'bền bỉ'],
    colors: ['hồng', 'đỏ', 'cam', 'trắng'],
    seasons: ['all_year'],
    images: [img('1559181567-c3190baa3e5a', 'hoa-bong-giay-kep')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất thoát nước. Tưới vừa phải và bón phân ít đạm để kích thích ra hoa thay vì lá.',
      'Plant in full sun with well-drained soil. Water moderately and apply low-nitrogen fertilizer to encourage flowering over foliage.',
    ),
    culturalSignificance: cultural(
      'Hoa bông giấy là biểu tượng của sự nhiệt huyết và đam mê trong cuộc sống của người Việt. Cây thường được trồng ở cổng nhà và tường rào tạo nên cảnh sắc rực rỡ đặc trưng của vùng nhiệt đới.',
      'Bougainvillea is a symbol of passion and enthusiasm in Vietnamese life. The plant is often grown on house gates and fences, creating the vibrant scenery characteristic of the tropics.',
    ),
    popularityScore: 35,
  },
  {
    name: { vi: 'Hoa Tử La Lan', en: 'Lady of the Night Orchid' },
    scientificName: 'Brassavola nodosa',
    slug: 'hoa-tu-la-lan',
    description: {
      vi: 'Hoa Tử La Lan là loài lan đêm nổi tiếng với hương thơm ngào ngạt tỏa ra vào ban đêm, cánh hoa trắng mảnh mai tinh tế. Hoa nở chủ yếu vào mùa xuân và tỏa hương thơm mạnh nhất khi trời mát.',
      en: 'Lady of the Night Orchid is a famous nocturnal orchid renowned for its intensely sweet fragrance released at night, with delicate slender white petals. It blooms primarily in spring and is most fragrant in cool temperatures.',
    },
    meanings: ['bí ẩn', 'quyến rũ', 'đêm tối', 'hương thơm'],
    colors: ['trắng', 'xanh lá'],
    seasons: ['spring'],
    images: [img('1582794543139-8ac70d8d2e98', 'hoa-tu-la-lan')],
    careInstructions: care(
      'Trồng trong giỏ thoáng khí hoặc gắn trên gỗ mục, nơi có ánh sáng tốt. Tưới khi rễ khô và cần bón phân loãng thường xuyên.',
      'Mount on driftwood or grow in airy baskets in good light. Water when roots dry and fertilize frequently with diluted fertilizer.',
    ),
    culturalSignificance: cultural(
      'Hoa Tử La Lan được các nhà sưu tập lan trân trọng vì hương thơm ban đêm độc đáo. Loài lan này gợi lên vẻ đẹp bí ẩn và quyến rũ của đêm nhiệt đới.',
      'Lady of the Night Orchid is treasured by orchid collectors for its unique nocturnal fragrance. This orchid evokes the mysterious and enchanting beauty of tropical nights.',
    ),
    popularityScore: 30,
  },
  {
    name: { vi: 'Hoa Bàng Vuông', en: 'Sea Poison Tree' },
    scientificName: 'Barringtonia asiatica',
    slug: 'hoa-bang-vuong',
    description: {
      vi: 'Hoa Bàng Vuông là loài hoa nhiệt đới lớn với những cụm nhị hoa dài màu hồng trắng nở về đêm. Hoa nở rất nhanh và rụng trước khi mặt trời mọc, tạo nên hiện tượng thiên nhiên kỳ diệu.',
      en: 'Sea Poison Tree produces large tropical flowers with long pink-white stamen clusters that bloom at night. The flowers open very quickly and fall before sunrise, creating a magical natural phenomenon.',
    },
    meanings: ['ngắn ngủi', 'quý giá', 'đêm tối', 'hiếm gặp'],
    colors: ['trắng', 'hồng'],
    seasons: ['summer'],
    images: [img('1522383225745-53eb9ee9ef27', 'hoa-bang-vuong')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, gần biển hoặc trong điều kiện khí hậu ẩm. Cây lớn chậm nhưng bền và ít cần chăm sóc.',
      'Plant in full sun near the coast or in humid climate conditions. The tree grows slowly but is durable and requires little care.',
    ),
    culturalSignificance: cultural(
      'Hoa Bàng Vuông nổi tiếng ở Côn Đảo và các đảo nhiệt đới của Việt Nam. Vẻ đẹp ngắn ngủi của hoa nhắc nhở về sự trân trọng từng khoảnh khắc trong cuộc sống.',
      'Sea Poison Tree is famous in Con Dao and tropical islands of Vietnam. The fleeting beauty of its flowers reminds us to cherish every moment in life.',
    ),
    popularityScore: 15,
  },
  {
    name: { vi: 'Hoa Cỏ May', en: 'Grass Bur' },
    scientificName: 'Chrysopogon aciculatus',
    slug: 'hoa-co-may',
    description: {
      vi: 'Hoa Cỏ May là loài cỏ hoang dã quen thuộc với những hạt nhỏ bám vào quần áo người đi qua. Dù là cỏ dại, Cỏ May lại mang ý nghĩa thơ ca về những kỷ niệm tuổi thơ và tình yêu trong sáng.',
      en: 'Grass Bur is a familiar wild grass with small seeds that cling to clothing of passersby. Although a weed, it carries poetic meaning about childhood memories and innocent love.',
    },
    meanings: ['kỷ niệm', 'gắn kết', 'tình yêu trong sáng', 'tuổi thơ'],
    colors: ['nâu', 'vàng'],
    seasons: ['autumn'],
    images: [img('1558906932-4e5aeefb0f1d', 'hoa-co-may')],
    careInstructions: care(
      'Cỏ May mọc tự nhiên ở đồng cỏ và bờ đê, không cần chăm sóc đặc biệt. Cây sinh trưởng mạnh trong điều kiện ánh sáng đầy đủ và đất khô.',
      'Grass Bur grows naturally in meadows and embankments, requiring no special care. The plant thrives in full light and dry soil conditions.',
    ),
    culturalSignificance: cultural(
      'Cỏ May đi vào thơ ca và âm nhạc Việt Nam như biểu tượng của tình yêu gắn bó và kỷ niệm tuổi thơ. Hình ảnh hạt cỏ may bám vào áo trở thành ẩn dụ cho tình cảm không rời.',
      'Grass Bur appears in Vietnamese poetry and music as a symbol of enduring love and childhood memories. The image of grass burs clinging to clothing became a metaphor for inseparable affection.',
    ),
    popularityScore: 10,
  },
  {
    name: { vi: 'Hoa Trâm Ổi', en: 'Lantana' },
    scientificName: 'Lantana camara',
    slug: 'hoa-tram-oi',
    description: {
      vi: 'Hoa Trâm Ổi mọc thành chùm nhỏ nhiều màu sắc, đặc biệt là sự kết hợp độc đáo giữa vàng, cam và đỏ trên cùng một chùm hoa. Cây nở hoa quanh năm và thu hút nhiều loài bướm đến thăm vườn.',
      en: 'Lantana blooms in small multi-colored clusters, notably the unique combination of yellow, orange, and red on the same flower head. The plant blooms year-round and attracts many butterfly species to the garden.',
    },
    meanings: ['đa dạng', 'vui tươi', 'thu hút', 'hoạt bát'],
    colors: ['vàng', 'cam', 'hồng', 'đỏ'],
    seasons: ['all_year'],
    images: [img('1525310072745-f49212b5ac6d', 'hoa-tram-oi')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất thoát nước. Cây chịu hạn tốt và ít cần chăm sóc, chỉ cần cắt tỉa để kiểm soát hình dạng.',
      'Plant in full sun with well-drained soil. Drought-tolerant and low-maintenance, only needing pruning to control shape.',
    ),
    culturalSignificance: cultural(
      'Hoa Trâm Ổi là loài cây dân dã quen thuộc ở nông thôn Việt Nam, thường mọc ven đường và trong vườn nhà. Dù đơn giản nhưng hoa mang lại màu sắc vui tươi và sức sống cho không gian xung quanh.',
      'Lantana is a folk plant familiar in Vietnamese rural areas, often growing along roadsides and in home gardens. Though simple, the flowers bring cheerful colors and vitality to surrounding spaces.',
    ),
    popularityScore: 20,
  },
  {
    name: { vi: 'Hoa Khế', en: 'Star Fruit Blossom' },
    scientificName: 'Averrhoa carambola',
    slug: 'hoa-khe',
    description: {
      vi: 'Hoa Khế là những bông hoa nhỏ màu tím hồng mọc thành chùm trên thân cây, tiền thân của những quả khế chua ngọt. Hoa nhỏ xinh nhưng nở nhiều và tạo nên cảnh sắc độc đáo trên thân cây khế gia đình.',
      en: 'Star Fruit Blossom consists of small pink-purple flowers growing in clusters on the trunk, precursors to the sweet-sour star fruit. The tiny flowers bloom abundantly, creating a unique sight on the familiar backyard tree.',
    },
    meanings: ['quê hương', 'ký ức', 'bình dị', 'hương vị'],
    colors: ['tím', 'hồng'],
    seasons: ['spring'],
    images: [img('1597848212624-a19eb35e2651', 'hoa-khe')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất màu mỡ và thoát nước. Tưới đều mùa khô và bón phân hữu cơ để cây sai quả.',
      'Plant in full sun with fertile, well-drained soil. Water regularly during dry season and apply organic fertilizer for better fruit production.',
    ),
    culturalSignificance: cultural(
      'Cây khế và hoa khế gắn liền với tuổi thơ và ký ức quê nhà của nhiều người Việt. Hình ảnh cây khế ăn trái trong sân nhà là biểu tượng của cuộc sống bình dị và ấm cúng.',
      'The star fruit tree and its blossoms are associated with the childhood and homeland memories of many Vietnamese people. The image of a fruit-bearing star fruit tree in the courtyard symbolizes a simple and warm family life.',
    ),
    popularityScore: 15,
  },
  {
    name: { vi: 'Hoa Phúc Bồn Tử', en: 'Raspberry Blossom' },
    scientificName: 'Rubus idaeus',
    slug: 'hoa-phuc-bon-tu',
    description: {
      vi: 'Hoa Phúc Bồn Tử là những bông hoa trắng nhỏ xinh của cây mâm xôi, nở vào mùa xuân báo hiệu mùa quả chín đỏ mọng. Hoa nhỏ nhắn nhưng hấp dẫn nhiều loài ong và bướm đến thụ phấn.',
      en: 'Raspberry Blossom consists of small delicate white flowers heralding the season of red juicy berries in spring. The tiny flowers attract many bee and butterfly species for pollination.',
    },
    meanings: ['ngọt ngào', 'hy vọng', 'tươi mới', 'phồn thịnh'],
    colors: ['trắng', 'hồng nhạt'],
    seasons: ['spring'],
    images: [img('1558618666-fcd25c85cd64', 'hoa-phuc-bon-tu')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất chua nhẹ và giàu hữu cơ. Tưới đều và cắt tỉa cành già sau mỗi vụ thu hoạch.',
      'Plant in full sun with slightly acidic, organic-rich soil. Water regularly and prune old canes after each harvest.',
    ),
    culturalSignificance: cultural(
      'Hoa và quả mâm xôi tượng trưng cho sự ngọt ngào và phong phú của thiên nhiên. Tại Việt Nam, mâm xôi ngày càng được trồng trong các vườn nhà ở vùng cao nguyên.',
      'Raspberry flowers and fruit symbolize the sweetness and abundance of nature. In Vietnam, raspberries are increasingly grown in home gardens in highland areas.',
    ),
    popularityScore: 12,
  },
  {
    name: { vi: 'Hoa Chùm Ớt', en: 'Ornamental Pepper' },
    scientificName: 'Capsicum annuum',
    slug: 'hoa-chum-ot',
    description: {
      vi: 'Hoa Chùm Ớt là những bông hoa trắng nhỏ của cây ớt cảnh, tiền thân của những quả ớt đỏ tươi bắt mắt. Cây vừa có hoa đẹp vừa có quả cảnh đẹp, phù hợp trang trí ban công và sân vườn.',
      en: 'Ornamental Pepper produces small white flowers that precede the eye-catching bright red ornamental fruits. The plant features both beautiful flowers and decorative fruits, perfect for balcony and garden decoration.',
    },
    meanings: ['sinh động', 'đa năng', 'nổi bật', 'nhiệt huyết'],
    colors: ['trắng', 'đỏ'],
    seasons: ['summer', 'autumn'],
    images: [img('1601004890843-c1f4f3e8af61', 'hoa-chum-ot')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất thoát nước. Tưới đều đặn và bón phân hữu cơ để cây ra nhiều quả cảnh đẹp.',
      'Plant in full sun with well-drained soil. Water regularly and apply organic fertilizer for abundant ornamental fruit production.',
    ),
    culturalSignificance: cultural(
      'Cây ớt cảnh ngày càng phổ biến trong văn hóa trang trí nhà cửa hiện đại tại Việt Nam. Màu đỏ tươi của quả mang ý nghĩa may mắn và được nhiều gia đình yêu thích.',
      'Ornamental pepper is increasingly popular in modern home decoration culture in Vietnam. The bright red color of the fruits carries auspicious meaning and is loved by many families.',
    ),
    popularityScore: 18,
  },
  {
    name: { vi: 'Hoa Râm Bụt', en: 'Hardy Hibiscus' },
    scientificName: 'Hibiscus moscheutos',
    slug: 'hoa-ram-but',
    description: {
      vi: 'Hoa Râm Bụt Hardy là giống dâm bụt lớn với hoa khổng lồ có thể đạt đường kính 30cm, màu sắc ấn tượng từ hồng đến đỏ. Đây là loài hoa đặc biệt thu hút sự chú ý ngay từ cái nhìn đầu tiên.',
      en: 'Hardy Hibiscus is a large hibiscus cultivar with enormous flowers that can reach 30cm in diameter, in impressive colors ranging from pink to red. This spectacular flower commands attention at first glance.',
    },
    meanings: ['vẻ đẹp to lớn', 'ấn tượng', 'quyến rũ', 'nổi bật'],
    colors: ['hồng', 'trắng', 'đỏ'],
    seasons: ['summer'],
    images: [img('1574684891174-df5aa67e6b2d', 'hoa-ram-but')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất giàu dinh dưỡng và ẩm. Tưới nhiều vào mùa hè nóng và bón phân hữu cơ định kỳ.',
      'Plant in full sun with nutrient-rich, moist soil. Water abundantly in hot summer and apply organic fertilizer periodically.',
    ),
    culturalSignificance: cultural(
      'Hoa dâm bụt là quốc hoa của Malaysia và được trân trọng rộng rãi trong khu vực Đông Nam Á. Tại Việt Nam, dâm bụt thường được trồng làm hàng rào sống và trang trí đường phố.',
      'Hibiscus is the national flower of Malaysia and widely revered throughout Southeast Asia. In Vietnam, hibiscus is commonly grown as living hedges and street decorations.',
    ),
    popularityScore: 30,
  },
  {
    name: { vi: 'Hoa Mãn Đình Hồng Đỏ', en: 'Red Ginger' },
    scientificName: 'Alpinia purpurata',
    slug: 'hoa-man-dinh-hong-do',
    description: {
      vi: 'Hoa Mãn Đình Hồng Đỏ là loài gừng cảnh nhiệt đới với những cụm hoa đỏ thắm đứng thẳng như ngọn đuốc rực lửa. Hoa có thể cao đến 1-2 mét, tạo nên điểm nhấn ấn tượng trong vườn nhiệt đới.',
      en: 'Red Ginger is a tropical ornamental ginger with deep red flower clusters standing upright like blazing torches. The flowers can reach 1-2 meters in height, creating an impressive focal point in tropical gardens.',
    },
    meanings: ['mạnh mẽ', 'nhiệt đới', 'quyền uy', 'rực rỡ'],
    colors: ['đỏ'],
    seasons: ['all_year'],
    images: [img('1519619091416-f5bc0ad1e71d', 'hoa-man-dinh-hong-do')],
    careInstructions: care(
      'Trồng nơi có ánh sáng vừa đến đầy đủ, đất ẩm và giàu dinh dưỡng. Tưới thường xuyên và bón phân để cây ra hoa liên tục.',
      'Plant in moderate to full light with moist, nutrient-rich soil. Water frequently and fertilize for continuous blooming.',
    ),
    culturalSignificance: cultural(
      'Hoa gừng đỏ là biểu tượng của vùng nhiệt đới và được sử dụng nhiều trong các lễ hội và trang trí sự kiện. Hoa tượng trưng cho sức sống mãnh liệt và vẻ đẹp hoang dã của rừng nhiệt đới.',
      'Red Ginger is a symbol of the tropics and is widely used in festivals and event decorations. The flower symbolizes the powerful vitality and wild beauty of tropical forests.',
    ),
    popularityScore: 35,
  },
  {
    name: { vi: 'Hoa Thủy Trúc', en: 'Papyrus' },
    scientificName: 'Cyperus papyrus',
    slug: 'hoa-thuy-truc',
    description: {
      vi: 'Hoa Thủy Trúc là loài cây thủy sinh có thân thẳng và tán lá xòe như ô dù xanh mướt ở đỉnh. Cây không có hoa nổi bật nhưng hình dạng độc đáo như những chiếc lọng xanh tạo nên vẻ đẹp trang nhã.',
      en: 'Papyrus is an aquatic plant with straight stems and lush umbrella-like green fronds at the top. While lacking showy flowers, its unique parasol-like shape creates an elegant decorative beauty.',
    },
    meanings: ['thanh tao', 'trí thức', 'bền bỉ', 'lịch sử'],
    colors: ['xanh lá'],
    seasons: ['all_year'],
    images: [img('1558906932-4e5aeefb0f1d', 'hoa-thuy-truc')],
    careInstructions: care(
      'Trồng trong chậu ngập nước hoặc đặt ở nơi ẩm ướt với ánh sáng tốt. Thay nước thường xuyên để tránh tảo và giữ cây xanh tươi.',
      'Grow in water-submerged pots or place in a moist location with good light. Change water frequently to prevent algae and keep the plant healthy.',
    ),
    culturalSignificance: cultural(
      'Cây Thủy Trúc gắn liền với nền văn minh Ai Cập cổ đại qua việc làm giấy papyrus. Tại Việt Nam, cây được trồng trang trí ao hồ và khu vực thủy sinh vì vẻ đẹp trang nhã.',
      'Papyrus is associated with ancient Egyptian civilization through the making of papyrus paper. In Vietnam, the plant is grown to decorate ponds and aquatic areas for its elegant appearance.',
    ),
    popularityScore: 15,
  },
  {
    name: { vi: 'Hoa Cánh Bướm', en: 'Butterfly Flower' },
    scientificName: 'Bauhinia purpurea',
    slug: 'hoa-canh-buom',
    description: {
      vi: 'Hoa Cánh Bướm có hình dạng 5 cánh hoa tím hồng giống đôi cánh bướm đang bay, nở rộ vào mùa xuân. Cây thường được trồng làm cảnh ven đường và công viên vì tán hoa đẹp và bóng mát tốt.',
      en: 'Butterfly Flower has five pink-purple petals shaped like butterfly wings in flight, blooming abundantly in spring. The tree is commonly planted as roadside and park ornamentation for its beautiful flowering canopy and good shade.',
    },
    meanings: ['tự do', 'biến đổi', 'vẻ đẹp', 'nhẹ nhàng'],
    colors: ['tím', 'hồng'],
    seasons: ['spring'],
    images: [img('1587131782564-fe45de7c0c11', 'hoa-canh-buom')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ hoặc nửa nắng, đất thoát nước. Cây lớn nhanh và ít cần chăm sóc đặc biệt.',
      'Plant in full sun or partial shade with well-drained soil. The tree grows quickly and requires little special care.',
    ),
    culturalSignificance: cultural(
      'Hoa Cánh Bướm được trồng rộng rãi ở các thành phố nhiệt đới như Tp.HCM để tạo bóng mát và cảnh quan đẹp. Hoa tím hồng nở vào mùa xuân mang lại vẻ đẹp lãng mạn cho phố phường.',
      'Butterfly Flower is widely planted in tropical cities like Ho Chi Minh City for shade and beautiful scenery. Pink-purple spring blooms bring a romantic beauty to city streets.',
    ),
    popularityScore: 38,
  },
  {
    name: { vi: 'Hoa Trang Đỏ', en: 'Red Ixora' },
    scientificName: 'Ixora chinensis',
    slug: 'hoa-trang-do',
    description: {
      vi: 'Hoa Trang Đỏ là loài hoa nhiệt đới nổi tiếng với những chùm hoa đỏ thắm mọc thành cầu tròn rực rỡ. Cây nở hoa quanh năm và là loại cây trang trí phổ biến nhất trong vườn nhà và công trình cảnh quan.',
      en: 'Red Ixora is a tropical flower famous for its brilliant deep red blooms forming round ball-shaped clusters. It flowers year-round and is the most popular ornamental shrub in home gardens and landscaping projects.',
    },
    meanings: ['tình yêu', 'nhiệt huyết', 'may mắn', 'thịnh vượng'],
    colors: ['đỏ'],
    seasons: ['all_year'],
    images: [img('1574684891174-df5aa67e6b2d', 'hoa-trang-do')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất chua nhẹ và thoát nước. Tưới đều đặn và bón phân hữu cơ hoặc chuyên dụng mỗi tháng.',
      'Plant in full sun with slightly acidic, well-drained soil. Water regularly and apply organic or specialized fertilizer monthly.',
    ),
    culturalSignificance: cultural(
      'Hoa Trang Đỏ là một trong những loài hoa trang trí phổ biến nhất ở Việt Nam và Đông Nam Á. Màu đỏ tươi của hoa mang ý nghĩa may mắn và thường được trồng ở cơ quan, trường học.',
      'Red Ixora is one of the most popular ornamental flowers in Vietnam and Southeast Asia. The bright red color carries auspicious meaning and is often planted at offices and schools.',
    ),
    popularityScore: 32,
  },
  {
    name: { vi: 'Hoa Mộc Miên', en: 'Silk Cotton Flower' },
    scientificName: 'Ceiba pentandra',
    slug: 'hoa-moc-mien',
    description: {
      vi: 'Hoa Mộc Miên nở vào mùa xuân khi cây chưa có lá, những bông hoa đỏ cam to lớn đơn độc trên cành trần trông rất ấn tượng. Cây Mộc Miên lớn là biểu tượng của sức mạnh và lịch sử lâu đời.',
      en: 'Silk Cotton Flower blooms in spring before the leaves appear, with large solitary red-orange flowers on bare branches creating an impressive sight. The mature Silk Cotton tree is a symbol of strength and long history.',
    },
    meanings: ['hùng tráng', 'sức mạnh', 'lịch sử', 'anh hùng'],
    colors: ['đỏ', 'cam'],
    seasons: ['spring'],
    images: [img('1601004890843-c1f4f3e8af61', 'hoa-moc-mien')],
    careInstructions: care(
      'Cây lớn, trồng ở không gian rộng rãi nơi có nắng đầy đủ. Cây rất dễ trồng, chịu hạn tốt và ít cần chăm sóc khi đã lớn.',
      'A large tree, plant in spacious areas with full sun. Very easy to grow, drought-tolerant and requires little care once established.',
    ),
    culturalSignificance: cultural(
      'Cây Mộc Miên được xem là cây anh hùng trong văn hóa nhiều dân tộc Á Đông. Những cây Mộc Miên cổ thụ ở đình làng là chứng nhân lịch sử của cộng đồng qua nhiều thế hệ.',
      'The Silk Cotton Tree is regarded as a heroic tree in the culture of many East Asian peoples. Ancient Silk Cotton trees at village communal houses are historical witnesses of communities across generations.',
    ),
    popularityScore: 28,
  },
  {
    name: { vi: 'Hoa Hoàng Lan', en: 'Ylang-ylang' },
    scientificName: 'Cananga odorata',
    slug: 'hoa-hoang-lan',
    description: {
      vi: 'Hoa Hoàng Lan nổi tiếng với hương thơm quyến rũ nồng nàn, là nguyên liệu quý trong ngành nước hoa cao cấp thế giới. Những cánh hoa vàng xanh mảnh mai rủ xuống tạo nên vẻ đẹp duyên dáng và huyền bí.',
      en: 'Ylang-ylang is famous for its intensely intoxicating fragrance, a precious ingredient in the world\'s finest perfumes. Its slender pale yellow petals cascading downward create a graceful and mysterious beauty.',
    },
    meanings: ['quyến rũ', 'tình yêu', 'hương thơm', 'lãng mạn'],
    colors: ['vàng'],
    seasons: ['all_year'],
    images: [img('1625231657647-9b15e0e49a0a', 'hoa-hoang-lan')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất tơi xốp và thoát nước. Cây phát triển tốt ở vùng nhiệt đới và tỏa hương mạnh nhất vào buổi tối.',
      'Plant in full sun with loose, well-drained soil. The tree thrives in tropical regions and releases its strongest fragrance in the evening.',
    ),
    culturalSignificance: cultural(
      'Hoa Hoàng Lan được ví như "Nữ hoàng hương thơm" và là thành phần chính trong nước hoa Chanel No.5 huyền thoại. Ở Việt Nam, hoa được dùng để thờ cúng và làm nước hoa thảo mộc truyền thống.',
      'Ylang-ylang is called the "Queen of Fragrance" and is a key component in the legendary Chanel No.5 perfume. In Vietnam, the flower is used for worship and traditional herbal perfume-making.',
    ),
    popularityScore: 40,
  },
  {
    name: { vi: 'Hoa Lan Cattleya Tím', en: 'Purple Cattleya Orchid' },
    scientificName: "Cattleya 'Purple'",
    slug: 'hoa-lan-cattleya-tim',
    description: {
      vi: 'Hoa Lan Cattleya Tím là nữ hoàng của các loài lan với những bông hoa to lớn màu tím rực rỡ và hương thơm quyến rũ. Đây là giống lan được ưa chuộng nhất trong giới chơi lan quốc tế và Việt Nam.',
      en: 'Purple Cattleya Orchid is the queen of orchids with large, brilliantly purple flowers and an enchanting fragrance. It is the most coveted orchid variety among international and Vietnamese orchid enthusiasts.',
    },
    meanings: ['sang trọng', 'quyền quý', 'tình yêu đích thực', 'hoàn hảo'],
    colors: ['tím', 'hồng'],
    seasons: ['spring', 'winter'],
    images: [img('1582794543139-8ac70d8d2e98', 'hoa-lan-cattleya-tim')],
    careInstructions: care(
      'Trồng trong giỏ thoáng khí hoặc chậu đất nung, nơi có ánh sáng đầy đủ nhưng không trực tiếp. Tưới khi giá thể khô hoàn toàn và bón phân lan mỗi tuần mùa sinh trưởng.',
      'Grow in airy baskets or terracotta pots in bright but indirect light. Water only when the medium is completely dry and fertilize weekly with orchid food during the growing season.',
    ),
    culturalSignificance: cultural(
      'Lan Cattleya được mệnh danh là "Nữ hoàng của các loài lan" trong giới chơi lan toàn cầu. Tại Việt Nam, sở hữu một cây Cattleya nở hoa đẹp là niềm tự hào của những người đam mê trồng lan.',
      'Cattleya orchid is dubbed the "Queen of Orchids" in the global orchid-growing community. In Vietnam, owning a beautifully blooming Cattleya is a source of pride for passionate orchid growers.',
    ),
    popularityScore: 50,
  },
];
