// Unsplash URLs for real flower images - stable and high quality
const FLOWER_IMAGES: Record<string, string> = {
  'hoa-protea': 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&h=800&fit=crop',
  'hoa-anthurium': 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800&h=800&fit=crop',
  'hoa-heliconia': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop',
  'hoa-delphinium': 'https://images.unsplash.com/photo-1457089328109-e5d9bd499191?w=800&h=800&fit=crop',
  'hoa-snapdragon': 'https://images.unsplash.com/photo-1596438459194-f275867a88ed?w=800&h=800&fit=crop',
  'hoa-stock': 'https://images.unsplash.com/photo-1519378058457-4c29a0a2efac?w=800&h=800&fit=crop',
  'hoa-freesia': 'https://images.unsplash.com/photo-1518882605630-8eb392ed3632?w=800&h=800&fit=crop',
  'hoa-sweet-pea': 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&h=800&fit=crop',
  'hoa-scabiosa': 'https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=800&h=800&fit=crop',
  'hoa-clematis': 'https://images.unsplash.com/photo-1519378058457-4c29a0a2efac?w=800&h=800&fit=crop',
  'hoa-lotus-pink': 'https://images.unsplash.com/photo-1474557157379-8aa74a6ef541?w=800&h=800&fit=crop',
  'hoa-agapanthus': 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&h=800&fit=crop',
  'hoa-amaryllis': 'https://images.unsplash.com/photo-1518882605630-8eb392ed3632?w=800&h=800&fit=crop',
  'hoa-aster': 'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=800&h=800&fit=crop',
  'hoa-alstroemeria': 'https://images.unsplash.com/photo-1596438459194-f275867a88ed?w=800&h=800&fit=crop',
  'hoa-veronica': 'https://images.unsplash.com/photo-1457089328109-e5d9bd499191?w=800&h=800&fit=crop',
  'hoa-wax-flower': 'https://images.unsplash.com/photo-1519378058457-4c29a0a2efac?w=800&h=800&fit=crop',
  'hoa-statice': 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&h=800&fit=crop',
  'hoa-bouvardia': 'https://images.unsplash.com/photo-1518882605630-8eb392ed3632?w=800&h=800&fit=crop',
  'hoa-kangaroo-paw': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop',
  'hoa-billy-balls': 'https://images.unsplash.com/photo-1508619870634-e55696632d12?w=800&h=800&fit=crop',
  'hoa-yarrow': 'https://images.unsplash.com/photo-1519378058457-4c29a0a2efac?w=800&h=800&fit=crop',
  'hoa-astilbe': 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&h=800&fit=crop',
  'hoa-heather': 'https://images.unsplash.com/photo-1518882605630-8eb392ed3632?w=800&h=800&fit=crop',
  'hoa-leucospermum': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop',
  'hoa-banksia': 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&h=800&fit=crop',
  'hoa-amaranth': 'https://images.unsplash.com/photo-1596438459194-f275867a88ed?w=800&h=800&fit=crop',
  'hoa-gomphrena': 'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=800&h=800&fit=crop',
};

const img = (_id: string, slug: string, primary = true) => ({
  url: FLOWER_IMAGES[slug] ?? 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&h=800&fit=crop',
  publicId: `flowery/flowers/${slug}`,
  isPrimary: primary,
});
const care = (vi: string, en: string) => ({ vi, en });
const cultural = (vi: string, en: string) => ({ vi, en });

export const flowersBatch2 = [
  {
    name: { vi: 'Hoa Protea', en: 'Protea' },
    scientificName: 'Protea cynaroides',
    slug: 'hoa-protea',
    description: {
      vi: 'Hoa Protea là biểu tượng quốc gia của Nam Phi với hình dáng độc đáo giống như vương miện, mang vẻ đẹp hoang dã và hùng tráng. Mỗi bông hoa có đường kính lên đến 30 cm, thu hút mọi ánh nhìn bởi sự kỳ vĩ và màu sắc rực rỡ.',
      en: 'Protea is the national flower of South Africa, recognized by its crown-like shape that exudes wild and majestic beauty. Each bloom can reach up to 30 cm in diameter, commanding attention with its grandeur and vibrant colors.',
    },
    meanings: ['Sự dũng cảm và bản lĩnh', 'Sức mạnh và kiên định', 'Sự đa dạng và phong phú', 'Tinh thần hoang dã tự do'],
    colors: ['Đỏ hồng', 'Hồng đậm', 'Trắng kem', 'Vàng nhạt'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    images: [img('1558618666-fcd25c85cd64-abcde', 'hoa-protea')],
    careInstructions: care(
      'Trồng nơi có ánh sáng mạnh và đất thoát nước tốt, tưới nước vừa phải, tránh đất giàu phốt pho.',
      'Plant in full sun with well-draining soil, water moderately, and avoid phosphorus-rich fertilizers.',
    ),
    culturalSignificance: cultural(
      'Hoa Protea là biểu tượng quốc gia của Nam Phi, đại diện cho sự đa dạng và vẻ đẹp của đất nước này.',
      'The Protea is South Africa\'s national flower, symbolizing the country\'s diversity and natural beauty.',
    ),
    popularityScore: 62,
  },
  {
    name: { vi: 'Hoa Anthurium', en: 'Anthurium' },
    scientificName: 'Anthurium andraeanum',
    slug: 'hoa-anthurium',
    description: {
      vi: 'Hoa Anthurium nổi bật với lá bắc bóng láng hình tim, màu sắc tươi sáng và đuôi nhụy vàng vươn dài rất bắt mắt. Loài hoa này mang lại không khí nhiệt đới sang trọng và được ưa chuộng trong trang trí nội thất.',
      en: 'Anthurium stands out with its glossy heart-shaped spathes in vivid colors and a protruding yellow spadix. This tropical flower brings a luxurious ambiance and is widely favored for interior decoration.',
    },
    meanings: ['Tình yêu nồng nàn', 'Lòng hiếu khách', 'Sự thịnh vượng', 'Niềm đam mê'],
    colors: ['Đỏ tươi', 'Hồng san hô', 'Trắng tinh', 'Xanh lá'],
    seasons: ['all_year'],
    images: [img('1523348837708-15d4a09cfac2-fghij', 'hoa-anthurium')],
    careInstructions: care(
      'Đặt nơi có ánh sáng gián tiếp, tưới đều đặn để đất ẩm nhưng không úng, bón phân loãng mỗi tháng.',
      'Place in indirect light, water regularly to keep soil moist but not waterlogged, and fertilize monthly with diluted solution.',
    ),
    culturalSignificance: cultural(
      'Anthurium được coi là biểu tượng của lòng hiếu khách và tình yêu bền chặt ở nhiều nền văn hóa châu Á.',
      'Anthurium is considered a symbol of hospitality and lasting love in many Asian cultures.',
    ),
    popularityScore: 71,
  },
  {
    name: { vi: 'Hoa Heliconia', en: 'Heliconia' },
    scientificName: 'Heliconia rostrata',
    slug: 'hoa-heliconia',
    description: {
      vi: 'Hoa Heliconia mang dáng vẻ kỳ lạ và ấn tượng với những lá bắc màu đỏ cam rực rỡ xếp thành chuỗi giống như móng vuốt của loài chim thiên đường. Loài hoa nhiệt đới này thường được gọi là "hoa chuối chim thiên đường" và rất phổ biến trong các bó hoa trang trí.',
      en: 'Heliconia features striking and exotic bracts in vivid orange-red arranged like the claws of a bird of paradise. Often called "lobster claw" or "hanging heliconia," this tropical flower is very popular in decorative arrangements.',
    },
    meanings: ['Sự tự do và phóng khoáng', 'Cá tính độc đáo', 'Nhiệt huyết và năng lượng', 'Vẻ đẹp nhiệt đới'],
    colors: ['Đỏ cam', 'Vàng', 'Xanh lá nhiệt đới'],
    seasons: ['summer', 'all_year'],
    images: [img('1546961342-ea5f710fbe8b-klmno', 'hoa-heliconia')],
    careInstructions: care(
      'Cần ánh sáng đầy đủ, đất giàu dinh dưỡng và độ ẩm cao, tưới nhiều nước vào mùa hè.',
      'Requires full sun, rich and moist soil, and ample watering especially during summer months.',
    ),
    culturalSignificance: cultural(
      'Heliconia là loài hoa đặc trưng của vùng nhiệt đới, thường xuất hiện trong lễ hội và nghi lễ tại các quốc gia Trung và Nam Mỹ.',
      'Heliconia is a hallmark of tropical regions, frequently used in festivals and ceremonies across Central and South America.',
    ),
    popularityScore: 48,
  },
  {
    name: { vi: 'Hoa Amaryllis', en: 'Amaryllis' },
    scientificName: 'Hippeastrum',
    slug: 'hoa-amaryllis',
    description: {
      vi: 'Hoa Amaryllis nở thành từng chùm lớn với những cánh hoa to, bắt mắt, thường được trồng trong nhà vào mùa đông và lễ Giáng sinh. Sự kết hợp giữa màu sắc rực rỡ và hình dáng sang trọng khiến Amaryllis trở thành món quà tặng hoàn hảo.',
      en: 'Amaryllis blooms in large clusters of big, eye-catching petals and is often grown indoors during winter and the Christmas season. The combination of vivid colors and elegant form makes Amaryllis a perfect gift.',
    },
    meanings: ['Vẻ đẹp rực rỡ', 'Kiêu hãnh và tự hào', 'Thành công vượt khó', 'Tình yêu lãng mạn'],
    colors: ['Đỏ thẫm', 'Đỏ hồng', 'Trắng tinh', 'Cam sọc'],
    seasons: ['winter', 'spring'],
    images: [img('1508792526479-2c1e55416f7d-pqrst', 'hoa-amaryllis')],
    careInstructions: care(
      'Trồng trong chậu có đất thoát nước tốt, đặt nơi ấm áp nhiều ánh sáng, tưới đều khi đất khô.',
      'Plant in pots with well-draining soil, place in a warm sunny location, and water consistently when the soil dries out.',
    ),
    culturalSignificance: cultural(
      'Amaryllis là biểu tượng của Giáng sinh tại nhiều nước phương Tây, mang ý nghĩa hy vọng và vẻ đẹp giữa mùa đông.',
      'Amaryllis is a Christmas symbol in many Western countries, representing hope and beauty during winter.',
    ),
    popularityScore: 57,
  },
  {
    name: { vi: 'Hoa Hyacinth', en: 'Hyacinth' },
    scientificName: 'Hyacinthus orientalis',
    slug: 'hoa-hyacinth',
    description: {
      vi: 'Hoa Hyacinth tỏa hương thơm ngào ngạt và nở thành chùm dày đặc với các bông hoa nhỏ xếp chặt quanh cành, rất phổ biến vào mùa xuân. Màu sắc phong phú từ tím, xanh, hồng đến trắng khiến Hyacinth là loài hoa xuân được yêu thích nhất.',
      en: 'Hyacinth releases an intensely sweet fragrance and blooms in dense clusters of small florets tightly packed around the stem, making it a spring favorite. Its wide range of colors from purple and blue to pink and white makes it one of the most beloved spring flowers.',
    },
    meanings: ['Sự hồi sinh và tái sinh', 'Niềm vui và hạnh phúc', 'Lòng biết ơn chân thành', 'Tình bạn thủy chung'],
    colors: ['Tím nhạt', 'Xanh dương', 'Hồng phấn', 'Trắng tinh'],
    seasons: ['spring'],
    images: [img('1557804506-669a364fb9f8-uvwxy', 'hoa-hyacinth')],
    careInstructions: care(
      'Trồng củ vào mùa thu, đặt nơi có ánh sáng đầy đủ, tưới điều độ và để đất thoát nước tốt.',
      'Plant bulbs in autumn, place in full sun, water moderately, and ensure the soil drains well.',
    ),
    culturalSignificance: cultural(
      'Trong thần thoại Hy Lạp, Hyacinth gắn liền với câu chuyện tình bi thương của thần Apollo, là biểu tượng của sự sống và cái chết.',
      'In Greek mythology, Hyacinth is linked to the tragic love story of the god Apollo, symbolizing life and death.',
    ),
    popularityScore: 66,
  },
  {
    name: { vi: 'Hoa Gardenia (Dành Dành)', en: 'Gardenia' },
    scientificName: 'Gardenia jasminoides',
    slug: 'hoa-gardenia',
    description: {
      vi: 'Hoa Gardenia hay còn gọi là hoa Dành Dành nổi tiếng với hương thơm nồng nàn và những cánh hoa trắng muốt xếp chặt như nhung. Loài hoa này được trân trọng trong nhiều nền văn hóa vì vẻ đẹp thuần khiết và hương thơm quyến rũ.',
      en: 'Gardenia, also known as Cape Jasmine, is renowned for its rich, intoxicating fragrance and velvety white petals arranged in a dense swirl. This flower is cherished across many cultures for its pure beauty and captivating scent.',
    },
    meanings: ['Sự tinh khiết và trong trắng', 'Tình yêu bí mật', 'Niềm vui thuần túy', 'Sự tinh tế và sang trọng'],
    colors: ['Trắng tinh', 'Kem nhạt'],
    seasons: ['spring', 'summer'],
    images: [img('1566454544259-f4b41a30d9d1-abcde', 'hoa-gardenia')],
    careInstructions: care(
      'Cần đất chua giàu dinh dưỡng, tưới nước thường xuyên, giữ độ ẩm cao và tránh nắng gắt trực tiếp.',
      'Requires acidic nutrient-rich soil, frequent watering, high humidity, and protection from harsh direct sunlight.',
    ),
    culturalSignificance: cultural(
      'Gardenia được dùng trong lễ cưới và nghi lễ tôn giáo ở nhiều nước châu Á, tượng trưng cho sự tinh khiết và tình yêu vĩnh cửu.',
      'Gardenia is used in weddings and religious ceremonies across Asia, symbolizing purity and eternal love.',
    ),
    popularityScore: 70,
  },
  {
    name: { vi: 'Hoa Sweet Pea', en: 'Sweet Pea' },
    scientificName: 'Lathyrus odoratus',
    slug: 'hoa-sweet-pea',
    description: {
      vi: 'Hoa Sweet Pea là loài hoa leo mảnh mai với những bông hoa xinh xắn hình cánh bướm và hương thơm ngọt dịu, thường thấy trong vườn hoa mùa xuân. Màu sắc phong phú từ tím, hồng, đỏ đến trắng làm cho Sweet Pea trở thành lựa chọn yêu thích cho bó hoa và trang trí.',
      en: 'Sweet Pea is a delicate climbing flower with charming butterfly-shaped blooms and a soft, sweet fragrance, commonly found in spring gardens. Its rich palette of purple, pink, red, and white makes Sweet Pea a favorite choice for bouquets and decorations.',
    },
    meanings: ['Niềm vui và hạnh phúc nhỏ bé', 'Lời tạm biệt nhẹ nhàng', 'Sự cảm ơn chân thành', 'Ký ức ngọt ngào'],
    colors: ['Tím', 'Hồng phấn', 'Đỏ tươi', 'Trắng', 'Tím nhạt'],
    seasons: ['spring', 'summer'],
    images: [img('1487530811015-3780697d03f3-fghij', 'hoa-sweet-pea')],
    careInstructions: care(
      'Gieo hạt vào đầu xuân, cần cọc leo, đất tốt và tưới đều đặn, hái hoa thường xuyên để cây tiếp tục ra hoa.',
      'Sow seeds in early spring, provide a climbing support, use good soil with regular watering, and pick flowers often to encourage continuous blooming.',
    ),
    culturalSignificance: cultural(
      'Hoa Sweet Pea gắn liền với tháng sinh nhật tháng Tư tại Anh và thường được dùng trong những buổi tiễn biệt để thể hiện lòng biết ơn.',
      'Sweet Pea is associated with the April birth month in England and is often used in farewell occasions to express gratitude.',
    ),
    popularityScore: 44,
  },
  {
    name: { vi: 'Hoa Wisteria (Tử Đằng)', en: 'Wisteria' },
    scientificName: 'Wisteria sinensis',
    slug: 'hoa-wisteria',
    description: {
      vi: 'Hoa Wisteria hay Tử Đằng nở thành những chùm hoa dài buông rủ với màu tím lãng mạn và hương thơm nhẹ nhàng, tạo nên cảnh quan huyền ảo như trong cổ tích. Loài hoa leo này thường phủ kín giàn, tường và cầu cổ, trở thành điểm nhấn kiến trúc tuyệt đẹp.',
      en: 'Wisteria blooms in long cascading clusters of romantic purple florets with a gentle fragrance, creating an enchanting fairy-tale landscape. This climbing vine often covers trellises, walls, and old bridges, becoming a stunning architectural highlight.',
    },
    meanings: ['Tình yêu lãng mạn say đắm', 'Sự trường tồn và bất diệt', 'Vẻ đẹp huyền bí', 'Nhớ nhung và hoài niệm'],
    colors: ['Tím', 'Tím nhạt', 'Trắng tím', 'Xanh tím'],
    seasons: ['spring'],
    images: [img('1519671482749-fd09498836e7-klmno', 'hoa-wisteria')],
    careInstructions: care(
      'Cần giàn leo chắc chắn, đất thoát nước, cắt tỉa sau khi nở hoa để kiểm soát sinh trưởng.',
      'Requires a sturdy support structure, well-draining soil, and pruning after blooming to control growth.',
    ),
    culturalSignificance: cultural(
      'Wisteria là biểu tượng của tình yêu bất diệt và hoa xuân nổi tiếng tại Nhật Bản, thường xuất hiện trong thơ ca và hội họa truyền thống.',
      'Wisteria is a symbol of immortal love and a celebrated spring flower in Japan, often featured in traditional poetry and paintings.',
    ),
    popularityScore: 73,
  },
  {
    name: { vi: 'Hoa Stock', en: 'Stock Flower' },
    scientificName: 'Matthiola incana',
    slug: 'hoa-stock',
    description: {
      vi: 'Hoa Stock nổi tiếng với hương thơm ngọt ngào đặc trưng và những cụm hoa dày đặc trên thân cây thẳng đứng, thường thấy trong các bó hoa cắt cành. Màu sắc đa dạng từ tím, hồng, đỏ đến trắng và vàng kem khiến Stock là loài hoa được ưa chuộng trong công nghiệp hoa cắt cành.',
      en: 'Stock flower is well-known for its distinctively sweet fragrance and dense clusters of blooms on upright stems, commonly seen in cut flower arrangements. Its diverse colors from purple, pink, and red to white and cream make it a popular choice in the cut flower industry.',
    },
    meanings: ['Vẻ đẹp lâu bền', 'Hạnh phúc gia đình', 'Lòng chung thủy', 'Sự ấm áp và nhớ nhung'],
    colors: ['Tím nhạt', 'Hồng', 'Đỏ', 'Trắng', 'Vàng kem'],
    seasons: ['spring', 'winter'],
    images: [img('1490750967868-88df5691240e-pqrst', 'hoa-stock')],
    careInstructions: care(
      'Trồng nơi có nắng đầy đủ, đất thoát nước tốt, tưới vừa phải và tránh để đất quá ẩm.',
      'Grow in full sun with well-draining soil, water moderately, and avoid overwatering to prevent root rot.',
    ),
    culturalSignificance: cultural(
      'Hoa Stock được dùng phổ biến trong đám cưới châu Âu từ thời Trung cổ, tượng trưng cho hạnh phúc lâu dài và tình yêu vĩnh cửu.',
      'Stock flowers have been widely used in European weddings since the Middle Ages, symbolizing lasting happiness and eternal love.',
    ),
    popularityScore: 41,
  },
  {
    name: { vi: 'Hoa Anh Túc (Poppy)', en: 'Poppy' },
    scientificName: 'Papaver somniferum',
    slug: 'hoa-anh-tuc',
    description: {
      vi: 'Hoa Anh Túc với những cánh hoa mỏng manh óng ánh như lụa và màu đỏ rực rỡ là một trong những loài hoa đẹp nhất nhưng cũng mang nhiều ý nghĩa phức tạp trong lịch sử. Cánh hoa mong manh rung động trước gió nhưng lại chứa đựng sức sống mãnh liệt và vẻ đẹp không thể phủ nhận.',
      en: 'The Poppy, with its silky translucent petals and vivid red color, is one of the most beautiful flowers with a complex history of symbolism. Its delicate petals flutter in the breeze yet carry remarkable vitality and undeniable beauty.',
    },
    meanings: ['Tưởng nhớ và tri ân', 'Giấc ngủ và sự nghỉ ngơi', 'Vẻ đẹp phù du', 'Hy sinh và lòng dũng cảm'],
    colors: ['Đỏ tươi', 'Cam', 'Hồng', 'Trắng', 'Tím'],
    seasons: ['spring', 'summer'],
    images: [img('1525310072745-f49212b5ac6d-uvwxy', 'hoa-anh-tuc')],
    careInstructions: care(
      'Gieo hạt trực tiếp ngoài trời vào mùa xuân hoặc thu, cần đất thoát nước và ánh sáng đầy đủ.',
      'Sow seeds directly outdoors in spring or autumn, requiring well-draining soil and full sun exposure.',
    ),
    culturalSignificance: cultural(
      'Hoa Anh Túc là biểu tượng tưởng niệm chiến sĩ hy sinh trong Thế chiến I ở các nước phương Tây, đặc biệt tại Anh và Canada.',
      'The Poppy is a memorial symbol for fallen soldiers of World War I in Western countries, especially in the UK and Canada.',
    ),
    popularityScore: 55,
  },
  {
    name: { vi: 'Hoa Dâm Bụt', en: 'Hibiscus' },
    scientificName: 'Hibiscus rosa-sinensis',
    slug: 'hoa-dam-but',
    description: {
      vi: 'Hoa Dâm Bụt nổi bật với những cánh hoa lớn, màu sắc rực rỡ và nhụy hoa vươn dài đặc trưng, là loài hoa quen thuộc ở vùng nhiệt đới và cận nhiệt đới. Loài hoa này không chỉ đẹp mà còn có giá trị y học trong y học cổ truyền nhiều nước.',
      en: 'Hibiscus stands out with large, brightly colored petals and a characteristic elongated stamen, a flower familiar in tropical and subtropical regions. This flower is not only beautiful but also holds medicinal value in traditional medicine of many countries.',
    },
    meanings: ['Vẻ đẹp tinh tế', 'Tình yêu tinh khiết', 'Sức sống mạnh mẽ', 'May mắn và thịnh vượng'],
    colors: ['Đỏ tươi', 'Hồng', 'Vàng', 'Trắng', 'Tím'],
    seasons: ['summer', 'all_year'],
    images: [img('1502759683-a547d2d2-abcde', 'hoa-dam-but')],
    careInstructions: care(
      'Cần nhiều ánh sáng mặt trời, tưới đều đặn và bón phân thường xuyên vào mùa sinh trưởng.',
      'Needs plenty of sunlight, regular watering, and frequent fertilizing during the growing season.',
    ),
    culturalSignificance: cultural(
      'Hoa Dâm Bụt là quốc hoa của Malaysia, biểu tượng cho vẻ đẹp và lòng dũng cảm của người dân nơi đây.',
      'Hibiscus is the national flower of Malaysia, symbolizing the beauty and courage of its people.',
    ),
    popularityScore: 59,
  },
  {
    name: { vi: 'Hoa Hồng Môn', en: 'Flamingo Flower' },
    scientificName: 'Anthurium andraeanum',
    slug: 'hoa-hong-mon',
    description: {
      vi: 'Hoa Hồng Môn là tên gọi phổ biến tại Việt Nam cho cây Anthurium với lá bắc bóng láng màu đỏ hoặc hồng rực, đuôi nhụy vàng nổi bật. Loài hoa này được trồng rộng rãi trong nhà và văn phòng vì khả năng chịu bóng tốt và vẻ đẹp sang trọng lâu bền.',
      en: 'Flamingo Flower is the popular Vietnamese name for Anthurium, featuring glossy red or bright pink spathes with a contrasting yellow spadix. This flower is widely grown indoors and in offices due to its shade tolerance and lasting elegant beauty.',
    },
    meanings: ['Lòng hiếu khách', 'Tình yêu nồng nhiệt', 'Sự may mắn', 'Thịnh vượng và phồn thịnh'],
    colors: ['Đỏ tươi', 'Hồng đậm', 'Trắng', 'Xanh lá'],
    seasons: ['all_year'],
    images: [img('1559759255-351d4b7b9f7b-fghij', 'hoa-hong-mon')],
    careInstructions: care(
      'Đặt nơi có ánh sáng gián tiếp, tưới khi đất khô 2-3 cm, phun sương để duy trì độ ẩm không khí.',
      'Place in indirect light, water when the top 2-3 cm of soil is dry, and mist regularly to maintain humidity.',
    ),
    culturalSignificance: cultural(
      'Hoa Hồng Môn được ưa chuộng trong ngày Tết và lễ khánh thành ở Việt Nam vì màu đỏ mang ý nghĩa may mắn.',
      'Flamingo Flower is popular during Tết and opening ceremonies in Vietnam as its red color symbolizes good luck.',
    ),
    popularityScore: 68,
  },
  {
    name: { vi: 'Hoa Cúc Đại Đóa', en: 'Large Chrysanthemum' },
    scientificName: 'Chrysanthemum morifolium',
    slug: 'hoa-cuc-dai-doa',
    description: {
      vi: 'Hoa Cúc Đại Đóa là giống cúc có kích thước to lớn, cánh hoa dày và xếp chồng lên nhau tạo thành bông hoa đầy đặn rực rỡ, rất được ưa chuộng trong trang trí và làm hoa cắt cành. Giống cúc này thường được dùng trong các bó hoa cưới, lễ hội và nghi lễ truyền thống.',
      en: 'Large Chrysanthemum features oversized blooms with thick overlapping petals forming a lush and vibrant flower head, highly prized in decoration and as cut flowers. This variety is often used in wedding bouquets, festivals, and traditional ceremonies.',
    },
    meanings: ['Sự trường thọ', 'Lòng trung thành', 'Niềm vui và hân hoan', 'Phẩm giá cao quý'],
    colors: ['Vàng', 'Trắng', 'Đỏ thẫm', 'Tím nhạt', 'Hồng'],
    seasons: ['autumn', 'winter'],
    images: [img('1508610048659-a06b669d05e5-klmno', 'hoa-cuc-dai-doa')],
    careInstructions: care(
      'Trồng nơi có ánh sáng tốt, đất màu mỡ, tưới đều và cắt tỉa nhánh để hoa to hơn.',
      'Grow in good light with fertile soil, water consistently, and pinch side shoots to encourage larger blooms.',
    ),
    culturalSignificance: cultural(
      'Hoa Cúc là biểu tượng của hoàng gia Nhật Bản và được tôn vinh trong Lễ hội Hoa Cúc hàng năm, mang ý nghĩa trường thọ và cao quý.',
      'Chrysanthemum is the symbol of the Japanese imperial family and celebrated at the annual Chrysanthemum Festival, representing longevity and nobility.',
    ),
    popularityScore: 63,
  },
  {
    name: { vi: 'Hoa Lan Mokara', en: 'Mokara Orchid' },
    scientificName: 'Mokara',
    slug: 'hoa-lan-mokara',
    description: {
      vi: 'Hoa Lan Mokara là giống lan lai nổi tiếng với hoa đẹp, màu sắc tươi sáng và độ bền cao, rất phổ biến trong ngành hoa cắt cành tại Đông Nam Á. Lan Mokara có thể nở hoa quanh năm trong điều kiện khí hậu nhiệt đới ẩm, là niềm tự hào của ngành trồng hoa Singapore.',
      en: 'Mokara Orchid is a famous hybrid orchid known for its beautiful, colorful, and long-lasting flowers, very popular in the cut flower industry in Southeast Asia. Mokara can bloom year-round in humid tropical climates and is a pride of Singapore\'s floriculture industry.',
    },
    meanings: ['Vẻ đẹp kiêu sa', 'Tình yêu mãnh liệt', 'Sự hoàn hảo', 'Niềm tự hào và danh dự'],
    colors: ['Đỏ', 'Cam', 'Vàng', 'Hồng', 'Tím'],
    seasons: ['all_year'],
    images: [img('1546430498-6963caa3d86d-pqrst', 'hoa-lan-mokara')],
    careInstructions: care(
      'Cần ánh sáng mạnh, tưới 2-3 lần/tuần, bón phân định kỳ và đảm bảo thoáng khí cho rễ.',
      'Requires bright light, watering 2-3 times per week, regular fertilizing, and good air circulation around roots.',
    ),
    culturalSignificance: cultural(
      'Lan Mokara là loài hoa đặc trưng của Singapore, thường được dùng trong các sự kiện ngoại giao và lễ hội quốc gia.',
      'Mokara Orchid is a representative flower of Singapore, commonly used in diplomatic events and national celebrations.',
    ),
    popularityScore: 54,
  },
  {
    name: { vi: 'Hoa Lan Vũ Nữ (Dancing Lady)', en: 'Dancing Lady Orchid' },
    scientificName: 'Oncidium',
    slug: 'hoa-lan-vu-nu',
    description: {
      vi: 'Hoa Lan Vũ Nữ mang tên gợi cảm hình ảnh những vũ nữ đang nhảy múa, với những bông hoa nhỏ màu vàng nâu xếp thành chùm dài, uyển chuyển như điệu múa. Loài lan này rất dễ chăm sóc và thường nở hoa dài ngày, là lựa chọn lý tưởng cho người mới trồng lan.',
      en: 'Dancing Lady Orchid evokes the image of dancing ballerinas with small golden-brown flowers arranged in long graceful sprays. This orchid is easy to care for and often blooms for extended periods, making it ideal for beginner orchid growers.',
    },
    meanings: ['Sự duyên dáng và thanh lịch', 'Niềm vui sống', 'Tự do và nhẹ nhàng', 'Vẻ đẹp trong sáng'],
    colors: ['Vàng', 'Vàng nâu', 'Nâu đốm vàng'],
    seasons: ['spring', 'autumn', 'all_year'],
    images: [img('1502816840809-87ec70b6f389-uvwxy', 'hoa-lan-vu-nu')],
    careInstructions: care(
      'Đặt nơi có ánh sáng vừa phải, tưới khi giá thể gần khô hoàn toàn, bón phân nhẹ mỗi 2 tuần.',
      'Place in moderate light, water when the growing medium is nearly dry, and fertilize lightly every 2 weeks.',
    ),
    culturalSignificance: cultural(
      'Lan Vũ Nữ được ưa chuộng ở nhiều quốc gia châu Á vì vẻ đẹp thanh thoát, thường dùng trong trang trí không gian sống và văn phòng.',
      'Dancing Lady Orchid is popular in many Asian countries for its graceful beauty and is often used to decorate living spaces and offices.',
    ),
    popularityScore: 49,
  },
  {
    name: { vi: 'Hoa Cúc Tana', en: 'Tana Chrysanthemum' },
    scientificName: 'Tanacetum parthenium',
    slug: 'hoa-cuc-tana',
    description: {
      vi: 'Hoa Cúc Tana là giống cúc nhỏ xinh với những bông hoa trắng viền cánh và nhụy vàng, nở thành chùm tươi tắn, thường được dùng làm hoa nền trong bó hoa. Loài hoa này có mùi hương nhẹ đặc trưng và thường được dùng trong y học dân gian như một loại thảo dược.',
      en: 'Tana Chrysanthemum is a charming small flower with white petals and a yellow center, blooming in fresh clusters often used as filler flowers in bouquets. This flower has a distinctive mild fragrance and is also used in folk medicine as an herbal remedy.',
    },
    meanings: ['Sự tươi mới và trong sáng', 'Bình an và tĩnh lặng', 'Sức khỏe và sức sống', 'Tình bạn thân thiết'],
    colors: ['Trắng', 'Vàng nhạt'],
    seasons: ['spring', 'summer'],
    images: [img('1490750967868-88df5691240e-abcde', 'hoa-cuc-tana')],
    careInstructions: care(
      'Trồng nơi có ánh sáng tốt, đất thoát nước, tưới vừa phải và cắt tỉa để cây phân nhánh nhiều hơn.',
      'Grow in good light with well-draining soil, water moderately, and prune to encourage bushier growth.',
    ),
    culturalSignificance: cultural(
      'Hoa Cúc Tana từng được dùng trong y học cổ đại Hy Lạp và La Mã để trị đau đầu, hiện nay vẫn được nghiên cứu về công dụng y học.',
      'Tana Chrysanthemum was used in ancient Greek and Roman medicine to treat headaches and is still studied for its medicinal properties today.',
    ),
    popularityScore: 36,
  },
  {
    name: { vi: 'Hoa Thạch Thảo (Aster)', en: 'Aster' },
    scientificName: 'Aster amellus',
    slug: 'hoa-thach-thao',
    description: {
      vi: 'Hoa Thạch Thảo hay Aster nở rộ vào mùa thu với những bông hoa hình ngôi sao nhiều cánh, màu tím, hồng và trắng rực rỡ, mang lại sắc màu cho khu vườn cuối mùa. Tên gọi Aster có nguồn gốc từ tiếng Hy Lạp có nghĩa là "ngôi sao", phản ánh đúng hình dáng đặc trưng của loài hoa này.',
      en: 'Aster blooms abundantly in autumn with star-shaped multi-petaled flowers in vivid purple, pink, and white, bringing color to the late-season garden. The name Aster comes from the Greek word for "star," accurately reflecting the distinctive shape of this flower.',
    },
    meanings: ['Sự kiên nhẫn và bền bỉ', 'Tình yêu muộn màng', 'Trí tuệ và minh mẫn', 'Lòng biết ơn'],
    colors: ['Tím', 'Hồng', 'Trắng', 'Xanh tím'],
    seasons: ['autumn'],
    images: [img('1508193638397-1cc5d9c85a5f-fghij', 'hoa-thach-thao')],
    careInstructions: care(
      'Trồng nơi có ánh sáng tốt, đất màu mỡ thoát nước, tưới đều và cắt tỉa sau khi ra hoa.',
      'Plant in full sun with fertile well-draining soil, water consistently, and cut back after flowering.',
    ),
    culturalSignificance: cultural(
      'Hoa Thạch Thảo là hoa sinh nhật của tháng 9, mang ý nghĩa trí tuệ và tình yêu trong thần thoại Hy Lạp cổ đại.',
      'Aster is the September birth flower, symbolizing wisdom and love in ancient Greek mythology.',
    ),
    popularityScore: 47,
  },
  {
    name: { vi: 'Hoa Trà Mi', en: 'Vietnamese Camellia' },
    scientificName: 'Camellia vietnamensis',
    slug: 'hoa-tra-mi',
    description: {
      vi: 'Hoa Trà Mi là loài hoa đặc hữu của Việt Nam, nở với những cánh hoa hồng đào mượt mà xếp đều đặn tạo nên vẻ đẹp thanh thoát và tinh tế. Đây là loài hoa quý hiếm chỉ phân bố ở một số vùng núi của Việt Nam, được xem là báu vật thiên nhiên cần được bảo tồn.',
      en: 'Vietnamese Camellia is an endemic species of Vietnam, blooming with smooth peach-pink petals arranged uniformly to create graceful and refined beauty. It is a rare flower found only in certain mountainous regions of Vietnam and considered a natural treasure in need of conservation.',
    },
    meanings: ['Vẻ đẹp thuần Việt', 'Sự tao nhã và tinh tế', 'Lòng yêu quê hương', 'Sức sống bền bỉ'],
    colors: ['Hồng đào', 'Hồng nhạt', 'Trắng hồng'],
    seasons: ['winter', 'spring'],
    images: [img('1548460456-e2c1c374a4d5-klmno', 'hoa-tra-mi')],
    careInstructions: care(
      'Trồng nơi có bóng nắng nhẹ, đất chua thoát nước, tưới đủ ẩm và bón phân chuyên dụng cho hoa trà.',
      'Plant in partial shade with acidic well-draining soil, maintain adequate moisture, and use specialized camellia fertilizer.',
    ),
    culturalSignificance: cultural(
      'Hoa Trà Mi là niềm tự hào của thực vật Việt Nam, xuất hiện trong nhiều tác phẩm thơ ca và hội họa truyền thống của dân tộc.',
      'Vietnamese Camellia is a botanical pride of Vietnam, appearing in many traditional poetry and paintings of the nation.',
    ),
    popularityScore: 52,
  },
  {
    name: { vi: 'Hoa Ngâu', en: 'Aglaia Flower' },
    scientificName: 'Aglaia duperreana',
    slug: 'hoa-ngau',
    description: {
      vi: 'Hoa Ngâu là loài hoa nhỏ xinh màu vàng nhạt với hương thơm nồng nàn đặc trưng, rất quen thuộc trong văn hóa Việt Nam. Loài hoa này thường được dùng để ướp trà và làm hương liệu, là một phần không thể thiếu trong đời sống văn hóa ẩm thực Việt.',
      en: 'Aglaia Flower is a small, delicate, pale yellow flower with a characteristic rich fragrance, very familiar in Vietnamese culture. This flower is often used to scent tea and as a fragrance ingredient, an indispensable part of Vietnamese culinary culture.',
    },
    meanings: ['Hương thơm ký ức', 'Sự gắn bó gia đình', 'Truyền thống và văn hóa', 'Giản dị mà thanh cao'],
    colors: ['Vàng nhạt', 'Vàng kem'],
    seasons: ['summer', 'autumn'],
    images: [img('1587334223957-76ef3f1df02e-pqrst', 'hoa-ngau')],
    careInstructions: care(
      'Trồng nơi có bóng nắng, đất màu mỡ ẩm, tưới đều và bón phân hữu cơ định kỳ.',
      'Grow in partial shade with moist fertile soil, water regularly, and apply organic fertilizer periodically.',
    ),
    culturalSignificance: cultural(
      'Hoa Ngâu gắn liền với trà thơm ngâu – đặc sản ẩm thực Bắc Bộ, biểu tượng cho sự tinh tế và văn hóa thưởng trà của người Việt.',
      'Aglaia Flower is associated with Ngâu-scented tea, a Northern Vietnamese specialty, symbolizing the sophistication and tea culture of the Vietnamese people.',
    ),
    popularityScore: 43,
  },
  {
    name: { vi: 'Hoa Sơn Trà', en: 'Chinese Hawthorn' },
    scientificName: 'Crataegus cuneata',
    slug: 'hoa-son-tra',
    description: {
      vi: 'Hoa Sơn Trà nở thành chùm trắng tinh khiết vào mùa xuân, sau đó kết quả đỏ tươi, là loài cây vừa có hoa đẹp vừa có quả dùng làm thuốc và thực phẩm. Cây Sơn Trà thường mọc ở vùng núi cao, là loài cây quen thuộc trong y học cổ truyền và ẩm thực Việt Nam.',
      en: 'Chinese Hawthorn blooms in pure white clusters in spring and then produces bright red berries, a plant with both beautiful flowers and fruits used in medicine and food. The hawthorn tree typically grows in mountainous regions and is a familiar plant in traditional medicine and Vietnamese cuisine.',
    },
    meanings: ['Hy vọng và sự khởi đầu', 'Tình yêu bảo vệ', 'Sức khỏe và trường thọ', 'Vẻ đẹp giản dị'],
    colors: ['Trắng tinh', 'Hồng nhạt'],
    seasons: ['spring'],
    images: [img('1490750967868-88df56912400-uvwxy', 'hoa-son-tra')],
    careInstructions: care(
      'Cây ưa khí hậu mát mẻ, đất tốt thoát nước, tưới vừa phải và cắt tỉa hàng năm sau mùa hoa.',
      'Prefers cool climates with well-draining soil, moderate watering, and annual pruning after the flowering season.',
    ),
    culturalSignificance: cultural(
      'Quả Sơn Trà là vị thuốc quan trọng trong đông y, dùng chữa nhiều bệnh tiêu hóa và tim mạch, được dùng từ hàng nghìn năm.',
      'Hawthorn berries are an important medicinal ingredient in traditional Chinese medicine, used to treat digestive and cardiovascular conditions for thousands of years.',
    ),
    popularityScore: 38,
  },
  {
    name: { vi: 'Hoa Kim Ngân (Honeysuckle)', en: 'Honeysuckle' },
    scientificName: 'Lonicera japonica',
    slug: 'hoa-kim-ngan',
    description: {
      vi: 'Hoa Kim Ngân là loài hoa leo với những bông hoa ống nhỏ màu trắng vàng nở thành đôi và tỏa hương thơm ngọt ngào quyến rũ, đặc biệt vào buổi tối. Loài hoa này không chỉ đẹp mà còn là vị thuốc quý trong y học cổ truyền, được dùng để kháng khuẩn và thanh nhiệt.',
      en: 'Honeysuckle is a climbing flower with small tubular white-yellow blooms appearing in pairs and releasing a sweet, alluring fragrance especially in the evening. This flower is not only beautiful but also a precious herb in traditional medicine, used for its antibacterial and cooling properties.',
    },
    meanings: ['Tình yêu ngọt ngào', 'Sự gắn bó bền chặt', 'Hạnh phúc gia đình', 'Ký ức tuổi thơ'],
    colors: ['Trắng vàng', 'Vàng nhạt', 'Hồng trắng'],
    seasons: ['spring', 'summer'],
    images: [img('1504567961333-be8f3b9e8c67-abcde', 'hoa-kim-ngan')],
    careInstructions: care(
      'Trồng nơi có ánh sáng tốt hoặc bóng nắng nhẹ, cần giàn leo, đất ẩm và tưới đều.',
      'Plant in full sun or partial shade, provide a climbing support, keep soil moist, and water regularly.',
    ),
    culturalSignificance: cultural(
      'Hoa Kim Ngân là vị thuốc quan trọng trong đông y Trung Quốc và Việt Nam, dùng trị cảm sốt, viêm họng và nhiều bệnh khác từ xa xưa.',
      'Honeysuckle is a key herb in Chinese and Vietnamese traditional medicine, used to treat fevers, sore throats, and various other ailments since ancient times.',
    ),
    popularityScore: 46,
  },
  {
    name: { vi: 'Hoa Thiên Lý', en: 'Telosma' },
    scientificName: 'Telosma cordata',
    slug: 'hoa-thien-ly',
    description: {
      vi: 'Hoa Thiên Lý là loài hoa leo có hương thơm thanh khiết dịu dàng, nở thành chùm nhỏ màu xanh vàng nhạt và là một phần không thể tách rời của ẩm thực và văn hóa Việt Nam. Không chỉ làm cảnh, hoa Thiên Lý còn là nguyên liệu nấu ăn phổ biến, thường dùng xào tỏi hoặc nấu canh.',
      en: 'Telosma is a climbing flower with a delicate, pure fragrance, blooming in small pale yellow-green clusters and is an inseparable part of Vietnamese cuisine and culture. Beyond decoration, Telosma flowers are a popular cooking ingredient, commonly stir-fried with garlic or used in soups.',
    },
    meanings: ['Sự trong sáng và giản dị', 'Tình cảm gia đình', 'Hương vị quê nhà', 'Sức sống mộc mạc'],
    colors: ['Xanh vàng nhạt', 'Vàng nhạt'],
    seasons: ['summer', 'autumn'],
    images: [img('1596040033229-2e98d7a31b7a-fghij', 'hoa-thien-ly')],
    careInstructions: care(
      'Trồng nơi có ánh sáng tốt, cần giàn leo chắc chắn, tưới đều và bón phân hữu cơ.',
      'Grow in good sunlight with a sturdy climbing support, water regularly, and apply organic fertilizer.',
    ),
    culturalSignificance: cultural(
      'Hoa Thiên Lý là biểu tượng của nét đẹp ẩm thực Bắc Bộ, thường gắn với hình ảnh giàn hoa trước cổng nhà và bữa cơm gia đình.',
      'Telosma flower is a symbol of Northern Vietnamese culinary culture, associated with the image of flower trellises at house entrances and family meals.',
    ),
    popularityScore: 42,
  },
  {
    name: { vi: 'Hoa Mộc (Osmanthus)', en: 'Osmanthus' },
    scientificName: 'Osmanthus fragrans',
    slug: 'hoa-moc',
    description: {
      vi: 'Hoa Mộc là loài hoa nhỏ với hương thơm ngào ngạt đặc trưng nổi tiếng từ xa xưa, được dùng để ướp trà và chế hương liệu cao cấp ở châu Á. Dù bông hoa nhỏ bé nhưng hương thơm của Mộc có thể lan tỏa xa, khiến loài hoa này trở thành biểu tượng của sự tinh tế và quý phái.',
      en: 'Osmanthus is a small flower renowned for its intensely sweet and distinctive fragrance, historically used to scent teas and create premium fragrances in Asia. Despite its tiny size, the scent of Osmanthus can travel far, making it a symbol of refinement and nobility.',
    },
    meanings: ['Hạnh phúc và may mắn', 'Tình yêu bền lâu', 'Sự quý phái và cao sang', 'Ký ức ngọt ngào'],
    colors: ['Vàng', 'Trắng vàng', 'Cam nhạt'],
    seasons: ['autumn'],
    images: [img('1508610048659-a06b669d05e5-klmno', 'hoa-moc')],
    careInstructions: care(
      'Cần ánh sáng đầy đủ hoặc bóng nắng nhẹ, đất tốt thoát nước, tưới vừa phải và bảo vệ khỏi gió lạnh.',
      'Requires full sun or partial shade with well-draining soil, moderate watering, and protection from cold winds.',
    ),
    culturalSignificance: cultural(
      'Hoa Mộc là biểu tượng hạnh phúc trong văn hóa Trung Hoa và Việt Nam, gắn liền với truyền thuyết Hằng Nga và cây quế trên cung trăng.',
      'Osmanthus is a happiness symbol in Chinese and Vietnamese culture, connected to the legend of Chang\'e and the cassia tree on the moon.',
    ),
    popularityScore: 50,
  },
  {
    name: { vi: 'Hoa Dạ Hương', en: 'Evening Primrose' },
    scientificName: 'Oenothera biennis',
    slug: 'hoa-da-huong',
    description: {
      vi: 'Hoa Dạ Hương nở về đêm với những cánh hoa vàng mỏng manh và tỏa hương thơm ngọt dịu vào buổi tối và ban đêm, tạo nên vẻ đẹp huyền bí và lãng mạn. Loài hoa này còn có giá trị y học cao, đặc biệt hạt của nó chứa dầu giàu axit béo omega-6 rất tốt cho sức khỏe.',
      en: 'Evening Primrose blooms at night with delicate yellow petals releasing a sweet fragrance in the evening and nighttime, creating a mysterious and romantic beauty. This flower also has high medicinal value, especially its seeds which contain oil rich in omega-6 fatty acids beneficial to health.',
    },
    meanings: ['Vẻ đẹp ban đêm', 'Sự bí ẩn và huyền diệu', 'Sức khỏe và chữa lành', 'Tình yêu thầm lặng'],
    colors: ['Vàng tươi', 'Vàng nhạt'],
    seasons: ['summer', 'autumn'],
    images: [img('1495462911434-be47104d70fa-pqrst', 'hoa-da-huong')],
    careInstructions: care(
      'Trồng nơi có ánh sáng tốt, đất khô ráo thoát nước, rất chịu hạn và ít cần chăm sóc.',
      'Plant in full sun with dry well-draining soil, very drought-tolerant and requires minimal care.',
    ),
    culturalSignificance: cultural(
      'Hoa Dạ Hương được người thổ dân châu Mỹ dùng trong y học từ lâu đời, hiện nay dầu hoa anh thảo được dùng rộng rãi trong y học hiện đại.',
      'Evening Primrose has been used by Native Americans in medicine for centuries, and evening primrose oil is now widely used in modern medicine.',
    ),
    popularityScore: 39,
  },
  {
    name: { vi: 'Hoa Hồng Nhung (Velvet Rose)', en: 'Velvet Rose' },
    scientificName: "Rosa 'Velvet'",
    slug: 'hoa-hong-nhung',
    description: {
      vi: 'Hoa Hồng Nhung là giống hoa hồng đặc biệt với cánh hoa có bề mặt nhung mịn và màu đỏ thẫm huyền bí, toát lên vẻ đẹp sang trọng và quyến rũ khó cưỡng. Đây là một trong những giống hoa hồng được yêu chuộng nhất trong trang trí và làm quà tặng dịp đặc biệt.',
      en: 'Velvet Rose is a special rose variety with a velvety smooth petal surface and deep mysterious red color, exuding an irresistibly luxurious and seductive beauty. It is one of the most beloved rose varieties for decoration and as gifts for special occasions.',
    },
    meanings: ['Tình yêu sâu sắc', 'Đam mê nồng cháy', 'Sự sang trọng và quý phái', 'Vẻ đẹp bí ẩn'],
    colors: ['Đỏ thẫm', 'Đỏ nhung'],
    seasons: ['spring', 'summer', 'autumn'],
    images: [img('1455793461560-59ca1de5f3b2-uvwxy', 'hoa-hong-nhung')],
    careInstructions: care(
      'Cần ánh sáng đầy đủ, đất phù sa màu mỡ, tưới gốc đều đặn và bón phân hồng chuyên dụng mỗi tháng.',
      'Needs full sun, fertile loamy soil, regular root watering, and specialized rose fertilizer applied monthly.',
    ),
    culturalSignificance: cultural(
      'Hoa Hồng Nhung là biểu tượng của tình yêu lãng mạn và đam mê, được dùng trong ngày Valentine và lễ kỷ niệm tình yêu trên toàn thế giới.',
      'Velvet Rose is a symbol of romantic love and passion, used on Valentine\'s Day and love anniversaries worldwide.',
    ),
    popularityScore: 78,
  },
  {
    name: { vi: 'Hoa Đỗ Quyên (Azalea)', en: 'Azalea' },
    scientificName: 'Rhododendron simsii',
    slug: 'hoa-do-quyen',
    description: {
      vi: 'Hoa Đỗ Quyên nở rực rỡ vào mùa xuân với vô số bông hoa nhỏ phủ kín cành nhánh, tạo nên cảnh tượng ngoạn mục với màu sắc từ đỏ, hồng đến tím và trắng. Loài hoa này gắn liền với hình ảnh mùa xuân núi rừng, thường nở trên sườn núi cao tạo nên thảm hoa tuyệt đẹp.',
      en: 'Azalea blooms brilliantly in spring with countless small flowers covering every branch, creating a spectacular display in colors ranging from red and pink to purple and white. This flower is associated with spring mountain scenery, often blooming on high slopes to create breathtaking flower carpets.',
    },
    meanings: ['Sự tiết độ và chừng mực', 'Tình yêu mong manh', 'Cảnh báo nguy hiểm', 'Vẻ đẹp rực rỡ ngắn ngủi'],
    colors: ['Đỏ', 'Hồng', 'Tím', 'Trắng', 'Cam'],
    seasons: ['spring'],
    images: [img('1490750967868-88df56912404-abcde', 'hoa-do-quyen')],
    careInstructions: care(
      'Cần đất chua thoát nước tốt, tưới nước mưa hoặc nước không có clo, đặt nơi bóng nắng nhẹ.',
      'Requires acidic well-draining soil, rainwater or chlorine-free water for irrigation, and partial shade placement.',
    ),
    culturalSignificance: cultural(
      'Hoa Đỗ Quyên là hoa thành phố của nhiều đô thị Trung Quốc và biểu tượng của mùa xuân trong thơ ca phương Đông.',
      'Azalea is the city flower of many Chinese cities and a symbol of spring in Eastern poetry.',
    ),
    popularityScore: 65,
  },
  {
    name: { vi: 'Hoa Tử Đằng', en: 'Chinese Wisteria' },
    scientificName: 'Wisteria sinensis',
    slug: 'hoa-tu-dang',
    description: {
      vi: 'Hoa Tử Đằng với chùm hoa tím buông rủ dài và hương thơm nhẹ nhàng là một trong những cảnh quan đẹp nhất mùa xuân tại các khu vườn cổ điển. Cây leo mạnh mẽ này có thể sống hàng trăm năm và phủ kín các công trình kiến trúc tạo nên khung cảnh như trong thế giới cổ tích.',
      en: 'Chinese Wisteria with its long cascading purple flower clusters and gentle fragrance is one of the most beautiful spring spectacles in classical gardens. This vigorous climber can live for hundreds of years and cover architectural structures, creating fairy-tale-like scenery.',
    },
    meanings: ['Tình yêu vĩnh cửu', 'Sự bất tử', 'Vẻ đẹp cổ điển', 'Nhớ nhung và hoài cổ'],
    colors: ['Tím', 'Tím nhạt', 'Trắng'],
    seasons: ['spring'],
    images: [img('1519671482749-fd09498836e8-fghij', 'hoa-tu-dang')],
    careInstructions: care(
      'Cần giàn leo chắc chắn, đất tốt và đủ ẩm, cắt tỉa mạnh tay vào mùa đông để kiểm soát kích thước.',
      'Requires a strong support structure, good moist soil, and hard pruning in winter to control size.',
    ),
    culturalSignificance: cultural(
      'Tử Đằng là chủ đề nổi bật trong hội họa và thơ ca Nhật Bản, nơi có vườn Tử Đằng nổi tiếng thế giới ở Ashikaga.',
      'Chinese Wisteria is a prominent subject in Japanese painting and poetry, with the world-famous Wisteria Garden at Ashikaga.',
    ),
    popularityScore: 72,
  },
  {
    name: { vi: 'Hoa Lan Vanda', en: 'Vanda Orchid' },
    scientificName: 'Vanda coerulea',
    slug: 'hoa-lan-vanda',
    description: {
      vi: 'Hoa Lan Vanda là giống lan quý hiếm với màu xanh dương kỳ diệu cực kỳ hiếm gặp trong thế giới hoa lan, là một trong những giống lan đẹp và quý giá nhất. Loài lan này đang đứng trước nguy cơ tuyệt chủng trong tự nhiên do săn bắt quá mức và mất môi trường sống.',
      en: 'Vanda Orchid is a precious rare orchid with a miraculous blue color extremely rare in the orchid world, one of the most beautiful and valuable orchid varieties. This orchid faces extinction in the wild due to over-collection and habitat loss.',
    },
    meanings: ['Sự hiếm quý và độc đáo', 'Tình yêu cao thượng', 'Vẻ đẹp không tì vết', 'Sức mạnh tinh thần'],
    colors: ['Xanh dương', 'Tím xanh', 'Trắng', 'Tím'],
    seasons: ['all_year'],
    images: [img('1546461342-ea5f710fbe8c-klmno', 'hoa-lan-vanda')],
    careInstructions: care(
      'Cần ánh sáng mạnh, tưới hàng ngày và đảm bảo thoáng khí tốt cho rễ khí sinh, bón phân đều đặn.',
      'Requires strong light, daily watering, excellent air circulation for aerial roots, and consistent fertilizing.',
    ),
    culturalSignificance: cultural(
      'Lan Vanda xanh là biểu tượng của nước Bhutan và là đề tài nghiên cứu bảo tồn quan trọng của quốc tế do nguy cơ tuyệt chủng.',
      'Blue Vanda Orchid is a symbol of Bhutan and an important subject of international conservation research due to its endangered status.',
    ),
    popularityScore: 61,
  },
  {
    name: { vi: 'Hoa Cúc Calimero', en: 'Calimero Chrysanthemum' },
    scientificName: "Chrysanthemum 'Calimero'",
    slug: 'hoa-cuc-calimero',
    description: {
      vi: 'Hoa Cúc Calimero là giống cúc nhỏ xinh với những bông hoa tròn đầy như quả bóng nhỏ, rất được ưa chuộng trong trang trí và làm hoa nền trong bó hoa. Giống cúc này rất đa dạng màu sắc và có độ bền cao khi cắt cành, thường được dùng trong ngành hoa thương mại.',
      en: 'Calimero Chrysanthemum is a charming small variety with round, ball-like flower heads, very popular for decoration and as filler flowers in bouquets. This variety offers a wide range of colors and excellent vase life when cut, commonly used in the commercial flower industry.',
    },
    meanings: ['Sự đáng yêu và dễ thương', 'Tình bạn vui vẻ', 'Niềm vui nhỏ bé', 'Sự tinh tế'],
    colors: ['Vàng', 'Trắng', 'Hồng', 'Đỏ', 'Tím'],
    seasons: ['autumn', 'winter', 'spring'],
    images: [img('1508610048659-a06b669d05e6-pqrst', 'hoa-cuc-calimero')],
    careInstructions: care(
      'Trồng nơi có ánh sáng tốt, đất thoát nước, tưới đều và bón phân cân đối để hoa to đẹp.',
      'Plant in good light with well-draining soil, water consistently, and apply balanced fertilizer for larger, more beautiful blooms.',
    ),
    culturalSignificance: cultural(
      'Cúc Calimero là giống hoa phổ biến trong ngành hoa cắt cành Hà Lan và được xuất khẩu đến nhiều nước trên thế giới.',
      'Calimero Chrysanthemum is a popular variety in the Dutch cut flower industry and is exported to many countries worldwide.',
    ),
    popularityScore: 45,
  },
  {
    name: { vi: 'Hoa Đinh Hương (Lilac)', en: 'Lilac' },
    scientificName: 'Syringa vulgaris',
    slug: 'hoa-dinh-huong',
    description: {
      vi: 'Hoa Đinh Hương hay Lilac nổi tiếng với hương thơm ngọt ngào đặc trưng và những chùm hoa tím lãng mạn nở rộ vào đầu mùa xuân, báo hiệu mùa ấm áp đến. Loài hoa này là biểu tượng của mùa xuân và tuổi trẻ ở nhiều nền văn hóa phương Tây.',
      en: 'Lilac is famous for its characteristically sweet fragrance and romantic purple clusters blooming in early spring, heralding the arrival of warm weather. This flower is a symbol of spring and youth in many Western cultures.',
    },
    meanings: ['Tình yêu đầu tiên', 'Mùa xuân và tuổi trẻ', 'Ký ức ngọt ngào', 'Sự thuần khiết'],
    colors: ['Tím nhạt', 'Tím', 'Trắng', 'Hồng nhạt'],
    seasons: ['spring'],
    images: [img('1557804506-669a364fb9f9-uvwxy', 'hoa-dinh-huong')],
    careInstructions: care(
      'Cần khí hậu mát mẻ và đất tốt thoát nước, tưới vừa phải, cắt tỉa sau khi nở hoa để chuẩn bị cho mùa sau.',
      'Requires cool climate and well-draining soil, moderate watering, and pruning after flowering to prepare for the next season.',
    ),
    culturalSignificance: cultural(
      'Hoa Đinh Hương là biểu tượng của thành phố Portsmouth (Mỹ) và nhà thơ Walt Whitman đã viết bài thơ nổi tiếng về loài hoa này.',
      'Lilac is the symbol of Portsmouth, USA, and the poet Walt Whitman wrote a famous poem about this flower.',
    ),
    popularityScore: 64,
  },
  {
    name: { vi: 'Hoa Tú Cầu Mini', en: 'Mini Hydrangea' },
    scientificName: "Hydrangea macrophylla 'Mini'",
    slug: 'hoa-tu-cau-mini',
    description: {
      vi: 'Hoa Tú Cầu Mini là phiên bản nhỏ xinh hơn của Tú Cầu thông thường, với những chùm hoa nhỏ nhắn dày đặc rất dễ thương và phù hợp cho không gian nhỏ. Loài hoa này thay đổi màu sắc theo độ pH của đất, từ xanh đến hồng, tạo nên sự thú vị cho người trồng.',
      en: 'Mini Hydrangea is a smaller and cuter version of the common Hydrangea, with compact dense flower clusters perfect for smaller spaces. This flower changes color based on soil pH, from blue to pink, creating excitement for growers.',
    },
    meanings: ['Lòng biết ơn', 'Sự chân thành', 'Hiểu biết và thấu cảm', 'Vẻ đẹp khiêm nhường'],
    colors: ['Xanh dương', 'Hồng', 'Trắng', 'Tím'],
    seasons: ['spring', 'summer'],
    images: [img('1490750967868-88df56912401-abcde', 'hoa-tu-cau-mini')],
    careInstructions: care(
      'Cần đất ẩm giàu mùn, bóng nắng nhẹ, tưới đều và bón phân chuyên dụng để điều chỉnh màu sắc hoa.',
      'Requires moist humus-rich soil, partial shade, consistent watering, and specialized fertilizer to adjust flower color.',
    ),
    culturalSignificance: cultural(
      'Hoa Tú Cầu rất phổ biến trong văn hóa cưới xin hiện đại và thường xuất hiện trong ảnh cưới vì vẻ đẹp lãng mạn và sang trọng.',
      'Hydrangea is very popular in modern wedding culture and often appears in wedding photography for its romantic and elegant beauty.',
    ),
    popularityScore: 76,
  },
  {
    name: { vi: 'Hoa Ngọc Trâm (Agapanthus)', en: 'Agapanthus' },
    scientificName: 'Agapanthus praecox',
    slug: 'hoa-ngoc-tram',
    description: {
      vi: 'Hoa Ngọc Trâm hay Agapanthus nở thành chùm hoa hình cầu thanh lịch với những bông hoa ống nhỏ màu xanh dương hoặc trắng, rất duyên dáng và sang trọng. Loài hoa này thích hợp trồng ven đường, trong vườn hoặc làm hoa cắt cành nhờ thân cao và bông hoa đẹp.',
      en: 'Agapanthus blooms in elegant spherical clusters with small tubular blue or white florets, very graceful and sophisticated. This flower is ideal for planting along roadsides, in gardens, or as cut flowers due to its tall stems and beautiful blooms.',
    },
    meanings: ['Tình yêu và vẻ đẹp', 'Sự kiên cường', 'Thịnh vượng và phồn thịnh', 'Vẻ đẹp thanh lịch'],
    colors: ['Xanh dương', 'Tím xanh', 'Trắng'],
    seasons: ['summer'],
    images: [img('1568605116527-4c71e3ccac66-fghij', 'hoa-ngoc-tram')],
    careInstructions: care(
      'Trồng nơi có ánh sáng tốt, đất thoát nước, tưới điều độ và bảo vệ khỏi sương giá.',
      'Plant in full sun with well-draining soil, water moderately, and protect from frost.',
    ),
    culturalSignificance: cultural(
      'Agapanthus là biểu tượng tình yêu và vẻ đẹp trong văn hóa châu Phi, được trồng rộng rãi ở Nam Phi và Địa Trung Hải.',
      'Agapanthus is a symbol of love and beauty in African culture, widely cultivated in South Africa and the Mediterranean.',
    ),
    popularityScore: 47,
  },
  {
    name: { vi: 'Hoa Lan Ý (Peace Lily)', en: 'Peace Lily' },
    scientificName: 'Spathiphyllum wallisii',
    slug: 'hoa-lan-y',
    description: {
      vi: 'Hoa Lan Ý hay Peace Lily nổi tiếng với hình dáng thanh lịch gồm lá mo trắng ôm lấy bông nhụy vàng xanh, là loài hoa trong nhà được yêu thích nhất thế giới. Ngoài vẻ đẹp, Lan Ý còn nổi tiếng với khả năng lọc không khí, loại bỏ các chất độc hại như ammoniac và benzen.',
      en: 'Peace Lily is famous for its elegant form with a white spathe cradling a pale yellow spadix, making it one of the world\'s most beloved indoor plants. Beyond beauty, Peace Lily is renowned for its air-purifying ability, removing harmful substances like ammonia and benzene.',
    },
    meanings: ['Hòa bình và yên tĩnh', 'Sự chữa lành', 'Hy vọng và sự phục hồi', 'Tinh thần thuần khiết'],
    colors: ['Trắng tinh', 'Trắng xanh'],
    seasons: ['all_year'],
    images: [img('1502816840809-87ec70b6f390-klmno', 'hoa-lan-y')],
    careInstructions: care(
      'Ưa bóng râm hoặc ánh sáng gián tiếp, tưới khi đất khô, phun sương và tránh để đất ngập úng.',
      'Prefers shade or indirect light, water when soil is dry, mist leaves, and avoid waterlogging.',
    ),
    culturalSignificance: cultural(
      'Hoa Lan Ý thường được tặng để chia buồn và cầu nguyện cho linh hồn người đã khuất trong nhiều nền văn hóa phương Tây.',
      'Peace Lily is often given as a sympathy flower and prayer for the souls of the departed in many Western cultures.',
    ),
    popularityScore: 67,
  },
  {
    name: { vi: 'Hoa Chuông (Bellflower)', en: 'Bellflower' },
    scientificName: 'Campanula medium',
    slug: 'hoa-chuong',
    description: {
      vi: 'Hoa Chuông với hình dáng như những chiếc chuông nhỏ treo lủng lẳng màu xanh tím và tím nhạt rất đặc trưng, thường thấy trong vườn hoa châu Âu. Những bông hoa hình chuông duyên dáng này nở thành từng chùm dọc theo thân cây tạo nên vẻ đẹp thơ mộng và nhẹ nhàng.',
      en: 'Bellflower, shaped like hanging small bells in blue-purple and pale purple hues, is a distinctive flower commonly seen in European gardens. These charming bell-shaped blooms appear in clusters along the stem, creating a poetic and gentle beauty.',
    },
    meanings: ['Lòng biết ơn', 'Sự không thay đổi', 'Tình yêu thủy chung', 'Sự khiêm nhường'],
    colors: ['Xanh tím', 'Tím nhạt', 'Trắng', 'Hồng'],
    seasons: ['spring', 'summer'],
    images: [img('1495462911434-be47104d70fb-pqrst', 'hoa-chuong')],
    careInstructions: care(
      'Trồng nơi có ánh sáng tốt hoặc bóng nắng nhẹ, đất thoát nước tốt và tưới điều độ.',
      'Plant in full sun or partial shade with well-draining soil and water moderately.',
    ),
    culturalSignificance: cultural(
      'Hoa Chuông là biểu tượng của lòng biết ơn và sự không thay đổi trong văn hóa Anh và Scotland, thường xuất hiện trong cổ thi.',
      'Bellflower is a symbol of gratitude and constancy in English and Scottish culture, often appearing in classical poetry.',
    ),
    popularityScore: 40,
  },
  {
    name: { vi: 'Hoa Cát Cánh (Balloon Flower)', en: 'Balloon Flower' },
    scientificName: 'Platycodon grandiflorus',
    slug: 'hoa-cat-canh',
    description: {
      vi: 'Hoa Cát Cánh nổi tiếng với nụ hoa phình tròn như bóng bay trước khi nở thành hoa hình sao 5 cánh màu xanh tím rực rỡ, rất thú vị và độc đáo. Đây cũng là loài thảo dược quý trong đông y Hàn Quốc và Trung Quốc, rễ được dùng làm thuốc trị ho và viêm họng.',
      en: 'Balloon Flower is famous for its puffy balloon-like buds before opening into a striking five-pointed star-shaped blue-purple flower, making it a fascinating and unique plant. It is also a precious medicinal herb in Korean and Chinese traditional medicine, with roots used to treat coughs and sore throats.',
    },
    meanings: ['Sự trung thực và đáng tin', 'Tình yêu bền lâu', 'Ký ức không phai', 'Sự bí ẩn hấp dẫn'],
    colors: ['Xanh tím', 'Tím', 'Trắng', 'Hồng'],
    seasons: ['summer'],
    images: [img('1558618049-7d38c31c82f5-uvwxy', 'hoa-cat-canh')],
    careInstructions: care(
      'Trồng nơi có ánh sáng tốt, đất thoát nước, tưới vừa phải và tránh làm xáo trộn rễ khi trưởng thành.',
      'Plant in full sun with well-draining soil, water moderately, and avoid disturbing the roots once established.',
    ),
    culturalSignificance: cultural(
      'Hoa Cát Cánh là biểu tượng của Hàn Quốc, xuất hiện trong nhiều bài dân ca và tranh vẽ truyền thống của đất nước này.',
      'Balloon Flower is a symbol of Korea, appearing in many folk songs and traditional paintings of the country.',
    ),
    popularityScore: 43,
  },
  {
    name: { vi: 'Hoa Lycoris Vàng', en: 'Golden Spider Lily' },
    scientificName: 'Lycoris aurea',
    slug: 'hoa-lycoris-vang',
    description: {
      vi: 'Hoa Lycoris Vàng nở đột ngột trên thân trần không có lá với những cánh hoa vàng kim uốn cong và nhụy dài vươn ra như chân nhện vàng óng ánh. Loài hoa bí ẩn này nở vào cuối hạ đầu thu và biến mất nhanh chóng, để lại ấn tượng sâu sắc về vẻ đẹp thoáng qua.',
      en: 'Golden Spider Lily blooms suddenly on leafless stems with golden curved petals and long protruding stamens resembling shimmering golden spider legs. This mysterious flower blooms in late summer to early autumn and disappears quickly, leaving a deep impression of fleeting beauty.',
    },
    meanings: ['Sự chia cắt và hoài niệm', 'Vẻ đẹp phù du', 'Sự bí ẩn', 'Ranh giới giữa hai thế giới'],
    colors: ['Vàng kim', 'Vàng rực'],
    seasons: ['autumn'],
    images: [img('1549880338-6f55cd4b4bef-abcde', 'hoa-lycoris-vang')],
    careInstructions: care(
      'Trồng củ vào cuối hè, nơi có ánh sáng đầy đủ, đất thoát nước và tưới ít khi cây không có lá.',
      'Plant bulbs in late summer in full sun with well-draining soil and water sparingly when the plant has no leaves.',
    ),
    culturalSignificance: cultural(
      'Lycoris gắn liền với truyền thuyết Phật giáo về đường đến cõi khác, thường được trồng ở nghĩa trang và chùa chiền ở Nhật Bản.',
      'Lycoris is connected to Buddhist legends about the path to the afterlife, often planted in cemeteries and temples in Japan.',
    ),
    popularityScore: 35,
  },
  {
    name: { vi: 'Hoa Hướng Dương Mini', en: 'Mini Sunflower' },
    scientificName: "Helianthus 'Teddy Bear'",
    slug: 'hoa-huong-duong-mini',
    description: {
      vi: 'Hoa Hướng Dương Mini là phiên bản nhỏ nhắn đáng yêu của hoa hướng dương thông thường, với những bông hoa vàng kép dày đặc và phong phú trên cây nhỏ gọn. Giống hoa này thích hợp cho chậu cảnh và vườn nhỏ, mang lại năng lượng tích cực và niềm vui rực rỡ.',
      en: 'Mini Sunflower is an adorable small version of the common sunflower, featuring dense double yellow blooms on a compact plant. This variety is perfect for pots and small gardens, bringing positive energy and vibrant joy.',
    },
    meanings: ['Niềm vui và hạnh phúc', 'Lòng trung thành', 'Năng lượng tích cực', 'Ánh sáng và hy vọng'],
    colors: ['Vàng tươi', 'Vàng đậm'],
    seasons: ['summer', 'autumn'],
    images: [img('1470509037663-253aebea5be0-fghij', 'hoa-huong-duong-mini')],
    careInstructions: care(
      'Cần nhiều ánh sáng mặt trời trực tiếp, đất thoát nước tốt, tưới đều và bón phân cân đối.',
      'Needs plenty of direct sunlight, well-draining soil, consistent watering, and balanced fertilizer.',
    ),
    culturalSignificance: cultural(
      'Hoa Hướng Dương là biểu tượng của niềm vui và lòng trung thành trong nhiều nền văn hóa, đặc biệt được yêu thích ở Ukraine.',
      'Sunflower is a symbol of joy and loyalty in many cultures, especially beloved in Ukraine.',
    ),
    popularityScore: 69,
  },
  {
    name: { vi: 'Hoa Cỏ Lau (Pampas Grass)', en: 'Pampas Grass' },
    scientificName: 'Cortaderia selloana',
    slug: 'hoa-co-lau',
    description: {
      vi: 'Hoa Cỏ Lau hay Pampas Grass với những bông hoa lông xù trắng bạc hoặc hồng nhạt cao vút, đã trở thành xu hướng trang trí nội thất và sự kiện hiện đại rất được ưa chuộng. Cây cỏ lau tạo ra cảnh quan thiên nhiên hoang sơ và thơ mộng, mang lại cảm giác nhẹ nhàng và tự do.',
      en: 'Pampas Grass, with its tall silvery-white or pale pink fluffy plumes, has become a very popular trend in modern interior decoration and event styling. This grass creates a wild and poetic natural landscape, evoking feelings of lightness and freedom.',
    },
    meanings: ['Sự tự do và phóng khoáng', 'Vẻ đẹp hoang dã', 'Tình yêu thuần khiết', 'Sức mạnh và bền bỉ'],
    colors: ['Trắng bạc', 'Hồng nhạt', 'Kem'],
    seasons: ['autumn', 'winter'],
    images: [img('1508139628636-1527ae38e6e9-klmno', 'hoa-co-lau')],
    careInstructions: care(
      'Rất dễ trồng, cần ánh sáng đầy đủ và đất thoát nước, cắt tỉa vào cuối đông để chuẩn bị cho mùa sinh trưởng mới.',
      'Very easy to grow, needs full sun and well-draining soil, and should be cut back in late winter to prepare for the new growing season.',
    ),
    culturalSignificance: cultural(
      'Cỏ Pampas là biểu tượng của đồng cỏ Nam Mỹ và đã trở thành biểu tượng của phong trào trang trí bohemian hiện đại.',
      'Pampas Grass is a symbol of South American grasslands and has become an icon of the modern bohemian decoration movement.',
    ),
    popularityScore: 58,
  },
  {
    name: { vi: 'Hoa Oải Hương Pháp', en: 'French Lavender' },
    scientificName: 'Lavandula stoechas',
    slug: 'hoa-oai-huong-phap',
    description: {
      vi: 'Hoa Oải Hương Pháp khác với oải hương thông thường ở phần tai hoa nổi bật trên đỉnh bông, tạo nên hình dáng độc đáo như chú bướm nhỏ đang đậu. Loài oải hương này có hương thơm đặc trưng mạnh hơn và phù hợp với khí hậu ấm hơn so với oải hương Anh.',
      en: 'French Lavender differs from common lavender with prominent petal bracts atop each flower head, creating a unique shape resembling a small butterfly perching. This lavender variety has a stronger characteristic fragrance and is more suited to warmer climates than English lavender.',
    },
    meanings: ['Sự bình yên', 'Tình yêu và sự tận tâm', 'Sức khỏe và sự chữa lành', 'Sự thanh lọc'],
    colors: ['Tím', 'Xanh tím', 'Hồng tím'],
    seasons: ['spring', 'summer'],
    images: [img('1499028344343-138537f0de06-pqrst', 'hoa-oai-huong-phap')],
    careInstructions: care(
      'Cần ánh sáng đầy đủ, đất khô cằn thoát nước tốt, ít tưới và cắt tỉa nhẹ sau khi nở hoa.',
      'Needs full sun, dry well-draining soil, infrequent watering, and light pruning after flowering.',
    ),
    culturalSignificance: cultural(
      'Oải Hương Pháp là biểu tượng của vùng Provence nước Pháp, nổi tiếng với những cánh đồng oải hương tím ngắt thu hút hàng triệu du khách.',
      'French Lavender is a symbol of the Provence region of France, famous for its endless purple lavender fields attracting millions of tourists.',
    ),
    popularityScore: 74,
  },
  {
    name: { vi: 'Hoa Cúc Mâm Xôi', en: 'Feverfew' },
    scientificName: 'Tanacetum parthenium',
    slug: 'hoa-cuc-mam-xoi',
    description: {
      vi: 'Hoa Cúc Mâm Xôi là giống cúc nhỏ nhắn với những bông hoa trắng cánh nhỏ bao quanh nhụy vàng tươi, nở thành chùm dày đặc trông như đĩa xôi trắng nên có tên gọi độc đáo này. Ngoài làm cảnh, đây cũng là loại thảo dược có lịch sử lâu đời trong điều trị đau nửa đầu.',
      en: 'Feverfew is a small delicate chrysanthemum with tiny white petals surrounding bright yellow centers, blooming in dense clusters resembling a plate of white rice, hence its charming Vietnamese name. Besides decoration, it is also an herb with a long history of use in treating migraines.',
    },
    meanings: ['Sức khỏe và sự bình phục', 'Sự giản dị đáng yêu', 'Tươi mới và trong sáng', 'Bảo vệ và chăm sóc'],
    colors: ['Trắng', 'Vàng nhạt'],
    seasons: ['spring', 'summer'],
    images: [img('1490750967868-88df56912402-uvwxy', 'hoa-cuc-mam-xoi')],
    careInstructions: care(
      'Trồng nơi có ánh sáng tốt, đất thoát nước và không cần nhiều phân bón, rất dễ tự gieo hạt.',
      'Plant in good sun with well-draining soil and minimal fertilizer needs; it self-seeds very easily.',
    ),
    culturalSignificance: cultural(
      'Cúc Mâm Xôi được dùng trong y học dân gian châu Âu từ thời cổ đại để trị đau đầu, sốt và viêm khớp.',
      'Feverfew has been used in European folk medicine since ancient times to treat headaches, fevers, and arthritis.',
    ),
    popularityScore: 32,
  },
  {
    name: { vi: 'Hoa Hồng Juliet', en: 'Juliet Rose' },
    scientificName: "Rosa 'Juliet'",
    slug: 'hoa-hong-juliet',
    description: {
      vi: 'Hoa Hồng Juliet là giống hoa hồng lai đặc biệt do nhà lai tạo David Austin phát triển qua 15 năm, nổi tiếng với hình dáng cốc tròn hoàn hảo và màu cam đào bơ quyến rũ. Đây là một trong những giống hoa hồng đắt giá nhất thế giới khi ra mắt, biểu tượng của sự hoàn hảo trong lai tạo hoa hồng.',
      en: 'Juliet Rose is a special hybrid rose developed by David Austin over 15 years, renowned for its perfectly rounded cup shape and enchanting peach-apricot color. It was one of the most expensive roses in the world at its debut and is a symbol of perfection in rose breeding.',
    },
    meanings: ['Tình yêu hoàn hảo', 'Sự sang trọng tột đỉnh', 'Vẻ đẹp không tuổi', 'Đam mê và nghệ thuật'],
    colors: ['Cam đào', 'Đào mơ', 'Hồng cam'],
    seasons: ['spring', 'summer', 'autumn'],
    images: [img('1566454544259-f4b41a30d9d2-abcde', 'hoa-hong-juliet')],
    careInstructions: care(
      'Cần ánh sáng tốt ít nhất 6 giờ/ngày, đất phù sa giàu dinh dưỡng, tưới gốc đều đặn và phòng trừ sâu bệnh.',
      'Needs at least 6 hours of good sunlight, nutrient-rich loamy soil, regular root watering, and pest prevention.',
    ),
    culturalSignificance: cultural(
      'Hoa Hồng Juliet được dùng rộng rãi trong đám cưới cao cấp trên toàn thế giới và là biểu tượng của ngành hoa hồng Anh.',
      'Juliet Rose is widely used in luxury weddings worldwide and is a symbol of the English rose industry.',
    ),
    popularityScore: 80,
  },
  {
    name: { vi: 'Hoa Scabiosa', en: 'Scabiosa' },
    scientificName: 'Scabiosa atropurpurea',
    slug: 'hoa-scabiosa',
    description: {
      vi: 'Hoa Scabiosa hay còn gọi là hoa ghim kim với những bông hoa hình cầu duyên dáng, cánh mỏng manh xếp thành lớp và nhụy nhô cao như ghim kim, thường có màu tím xanh và hồng tím. Loài hoa này thu hút rất nhiều bướm và ong, là nguồn mật phong phú trong vườn tự nhiên.',
      en: 'Scabiosa, also known as Pincushion flower, features graceful rounded blooms with delicate layered petals and protruding pin-like stamens, usually in blue-purple and pink-purple hues. This flower attracts many butterflies and bees and is a rich nectar source in natural gardens.',
    },
    meanings: ['Sự bình yên trong tâm hồn', 'Tình cảm nhớ nhung', 'Vẻ đẹp tinh tế', 'Sự vô tư và hồn nhiên'],
    colors: ['Tím xanh', 'Hồng tím', 'Trắng', 'Đỏ thẫm'],
    seasons: ['spring', 'summer', 'autumn'],
    images: [img('1519671482749-fd09498836e9-fghij', 'hoa-scabiosa')],
    careInstructions: care(
      'Trồng nơi có ánh sáng tốt, đất kiềm thoát nước, tưới vừa phải và loại bỏ hoa tàn để cây tiếp tục nở.',
      'Plant in full sun with alkaline well-draining soil, water moderately, and deadhead spent flowers to encourage continuous blooming.',
    ),
    culturalSignificance: cultural(
      'Hoa Scabiosa thường được dùng trong bó hoa đám cưới mang phong cách đồng quê và vườn tự nhiên, đặc biệt phổ biến tại châu Âu.',
      'Scabiosa is commonly used in rustic and garden-style wedding bouquets, particularly popular in Europe.',
    ),
    popularityScore: 37,
  },
  {
    name: { vi: 'Hoa Liatris', en: 'Liatris' },
    scientificName: 'Liatris spicata',
    slug: 'hoa-liatris',
    description: {
      vi: 'Hoa Liatris hay còn gọi là hoa lông cọ tím với những bông hoa nhỏ li ti màu tím nở dày đặc từ đỉnh xuống trên thân thẳng đứng cao, tạo nên hình dáng thẳng tắp rất ấn tượng. Điều thú vị là Liatris nở từ trên xuống dưới, ngược với hầu hết các loài hoa khác.',
      en: 'Liatris, also called Blazing Star or Gayfeather, features tiny purple florets densely blooming from top to bottom on tall upright stems, creating an impressively straight silhouette. What is fascinating is that Liatris blooms from top to bottom, opposite to most other flowers.',
    },
    meanings: ['Sự vui vẻ và hạnh phúc', 'Kiên cường và thẳng thắn', 'Tình yêu không mệt mỏi', 'Sức sống mạnh mẽ'],
    colors: ['Tím', 'Tím hồng', 'Trắng'],
    seasons: ['summer', 'autumn'],
    images: [img('1508193638397-1cc5d9c85a60-klmno', 'hoa-liatris')],
    careInstructions: care(
      'Trồng nơi có ánh sáng đầy đủ, đất khô thoát nước tốt, chịu hạn rất tốt và ít cần chăm sóc.',
      'Plant in full sun with dry well-draining soil; very drought-tolerant and requires minimal maintenance.',
    ),
    culturalSignificance: cultural(
      'Hoa Liatris là loài hoa bản địa của Bắc Mỹ, được thổ dân da đỏ dùng trong y học và trang trí lễ hội truyền thống.',
      'Liatris is a native North American flower used by Indigenous peoples in medicine and traditional ceremonial decoration.',
    ),
    popularityScore: 34,
  },
  {
    name: { vi: 'Hoa Astilbe', en: 'Astilbe' },
    scientificName: 'Astilbe × arendsii',
    slug: 'hoa-astilbe',
    description: {
      vi: 'Hoa Astilbe nở thành những bông bông nhỏ li ti như lông vũ mềm mại, màu hồng, đỏ, tím hoặc trắng, xếp thành chùm vươn cao rất thanh thoát và duyên dáng. Loài hoa này đặc biệt phù hợp với nơi có bóng râm và đất ẩm, thường dùng ven suối, ao hồ trong thiết kế vườn.',
      en: 'Astilbe blooms in tiny feathery florets in pink, red, purple, or white, arranged in tall graceful plumes of delicate elegance. This flower thrives especially in shaded areas with moist soil and is commonly used beside streams and ponds in garden design.',
    },
    meanings: ['Sự kiên nhẫn và chờ đợi', 'Tình yêu mãi mãi', 'Vẻ đẹp dịu dàng', 'Sự quyến rũ tinh tế'],
    colors: ['Hồng', 'Đỏ', 'Trắng', 'Tím đỏ'],
    seasons: ['spring', 'summer'],
    images: [img('1568605116527-4c71e3ccac67-pqrst', 'hoa-astilbe')],
    careInstructions: care(
      'Ưa bóng râm hoặc nắng nhẹ, đất ẩm giàu mùn, tưới thường xuyên và bón phân mùa xuân.',
      'Prefers shade or partial sun, moist humus-rich soil, frequent watering, and spring fertilizing.',
    ),
    culturalSignificance: cultural(
      'Astilbe được ưa chuộng trong thiết kế vườn Nhật Bản và vườn Anh quốc, thường xuất hiện trong bó hoa cưới phong cách vườn tự nhiên.',
      'Astilbe is favored in Japanese and English garden design and often appears in garden-style wedding bouquets.',
    ),
    popularityScore: 44,
  },
  {
    name: { vi: 'Hoa Veronica', en: 'Veronica' },
    scientificName: 'Veronica spicata',
    slug: 'hoa-veronica',
    description: {
      vi: 'Hoa Veronica hay Speedwell nở thành những gié hoa dài màu xanh tím hoặc hồng rực rỡ, thẳng đứng thanh thoát, là loài hoa thu hút bướm và ong rất hiệu quả. Cây Veronica rất dễ trồng và chăm sóc, thích hợp làm viền luống hoa hoặc trồng trong chậu.',
      en: 'Veronica, also known as Speedwell, blooms in long upright spikes of vivid blue-purple or pink, gracefully vertical and highly attractive to butterflies and bees. Veronica is very easy to grow and maintain, suitable as a border plant or in containers.',
    },
    meanings: ['Sự trung thành và tin tưởng', 'Tình bạn vững chắc', 'Sự dịu dàng và chăm sóc', 'Vẻ đẹp bền bỉ'],
    colors: ['Xanh tím', 'Tím', 'Hồng', 'Trắng'],
    seasons: ['spring', 'summer'],
    images: [img('1558618666-fcd25c85cd65-uvwxy', 'hoa-veronica')],
    careInstructions: care(
      'Trồng nơi có ánh sáng đầy đủ, đất thoát nước tốt, tưới đều và cắt tỉa sau khi nở hoa để cây ra hoa thêm lần nữa.',
      'Plant in full sun with well-draining soil, water consistently, and cut back after blooming to encourage a second flush of flowers.',
    ),
    culturalSignificance: cultural(
      'Hoa Veronica được đặt tên theo Thánh Veronica trong Công giáo và biểu tượng cho sự trung thành và tin tưởng trong văn hóa Kitô giáo.',
      'Veronica flower is named after Saint Veronica in Catholicism and symbolizes faithfulness and trust in Christian culture.',
    ),
    popularityScore: 31,
  },
];
