import type mongoose from 'mongoose';

type IdMap = Record<string, mongoose.Types.ObjectId>;

// Unsplash URLs for product images - stable and high quality
const PRODUCT_IMAGES: Record<string, string[]> = {
  'bo-hong-do': [
    'https://images.unsplash.com/photo-1455659817273-f96807779a8a?w=800&h=800&fit=crop',
    'https://images.unsplash.com/photo-1518882605630-8eb392ed3632?w=800&h=800&fit=crop',
  ],
  'gio-huong-duong': ['https://images.unsplash.com/photo-1551731409-43eb1d5846be?w=800&h=800&fit=crop'],
  'chau-lan-ho-diep': ['https://images.unsplash.com/photo-1566937169390-7be4c63b8395?w=800&h=800&fit=crop'],
  'bo-sen-hong': ['https://images.unsplash.com/photo-1526547541286-73a7aaa08f2a?w=800&h=800&fit=crop'],
  'hop-mix-pastel': [
    'https://images.unsplash.com/photo-1487530811176-3780de880c5d?w=800&h=800&fit=crop',
    'https://images.unsplash.com/photo-1574068468668-a05a11f871da?w=800&h=800&fit=crop',
  ],
  'bo-cam-tu-cau': ['https://images.unsplash.com/photo-1526485856375-d3ef15e69a58?w=800&h=800&fit=crop'],
  'bo-lavender-kho': ['https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=800&h=800&fit=crop'],
  'hop-tulip': [
    'https://images.unsplash.com/photo-1522057306223-8d6fce09994a?w=800&h=800&fit=crop',
    'https://images.unsplash.com/photo-1520412099551-62b6bafeb5bb?w=800&h=800&fit=crop',
  ],
  'chau-da-yen-thao': ['https://images.unsplash.com/photo-1562702099-b7d3b717fb07?w=800&h=800&fit=crop'],
  'bo-hoa-cuoi': ['https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=800&h=800&fit=crop'],
  'bo-ly-trang': ['https://images.unsplash.com/photo-1468327768560-75b778cbb551?w=800&h=800&fit=crop'],
  'canh-dao-tet': ['https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&h=800&fit=crop'],
  'lang-cuc-vang': ['https://images.unsplash.com/photo-1508784411316-02b8cd4d3a3a?w=800&h=800&fit=crop'],
  'bo-mix-8-3': ['https://images.unsplash.com/photo-1455587734955-081b22074882?w=800&h=800&fit=crop'],
  'bo-hong-vang': ['https://images.unsplash.com/photo-1548460542-2bbf50bec45d?w=800&h=800&fit=crop'],
  'bo-thien-dieu': ['https://images.unsplash.com/photo-1530575832922-40799e16a02e?w=800&h=800&fit=crop'],
  'gio-tinh-yeu-bien': ['https://images.unsplash.com/photo-1455659817273-f96807779a8a?w=800&h=800&fit=crop'],
  'bo-dong-tien': ['https://images.unsplash.com/photo-1475127486462-7bdd0d16c1e8?w=800&h=800&fit=crop'],
  'hop-sang-trong': [
    'https://images.unsplash.com/photo-1558652093-eae4cb42cf90?w=800&h=800&fit=crop',
    'https://images.unsplash.com/photo-1574068468668-a05a11f871da?w=800&h=800&fit=crop',
  ],
  'bo-mimosa': ['https://images.unsplash.com/photo-1583510553442-c0a7f7eb1e28?w=800&h=800&fit=crop'],
};

const img = (slug: string, i: number, primary = false) => ({
  url: PRODUCT_IMAGES[slug]?.[i - 1] ?? PRODUCT_IMAGES[slug]?.[0] ?? 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&h=800&fit=crop',
  publicId: `products/${slug}-${i}`,
  isPrimary: primary,
});

export function getProductsData(shopMap: IdMap, flowerMap: IdMap) {
  return [
    // === Hoa Sài Gòn (5 products) ===
    {
      shopId: shopMap['hoa-sai-gon'],
      flowerId: flowerMap['hoa-hong-do'],
      name: 'Bó Hồng Đỏ Cổ Điển',
      slug: 'bo-hong-do-co-dien',
      description: 'Bó 20 hoa hồng đỏ Ecuador cao cấp, biểu tượng tình yêu vĩnh cửu',
      price: 450000,
      category: 'bouquet' as const,
      flowerComposition: [{ flowerId: flowerMap['hoa-hong-do'], quantity: 20 }],
      images: [img('bo-hong-do', 1, true), img('bo-hong-do', 2)],
      customizationOptions: [
        { name: 'Giấy gói', options: [{ label: 'Kraft', priceModifier: 0 }, { label: 'Lụa', priceModifier: 30000 }] },
      ],
      occasions: ['valentines', 'anniversary', 'birthday'],
      emotions: ['romantic', 'passionate'],
      stock: { quantity: 50, unlimited: false },
      isAvailable: true,
      totalSold: 128,
      averageRating: 4.7,
      tags: ['hồng đỏ', 'tình yêu', 'lãng mạn', 'valentine'],
    },
    {
      shopId: shopMap['hoa-sai-gon'],
      flowerId: flowerMap['hoa-huong-duong'],
      name: 'Giỏ Hướng Dương Rạng Rỡ',
      slug: 'gio-huong-duong-rang-ro',
      description: 'Giỏ 10 hướng dương tươi sáng kết hợp baby trắng',
      price: 380000,
      category: 'basket' as const,
      flowerComposition: [
        { flowerId: flowerMap['hoa-huong-duong'], quantity: 10 },
        { flowerId: flowerMap['hoa-baby'], quantity: 5 },
      ],
      images: [img('gio-huong-duong', 1, true)],
      customizationOptions: [],
      occasions: ['birthday', 'graduation', 'get_well'],
      emotions: ['joyful', 'friendly'],
      stock: { quantity: 30, unlimited: false },
      isAvailable: true,
      totalSold: 85,
      averageRating: 4.5,
      tags: ['hướng dương', 'vui vẻ', 'sinh nhật'],
    },
    {
      shopId: shopMap['hoa-sai-gon'],
      flowerId: flowerMap['hoa-lan-ho-diep'],
      name: 'Chậu Lan Hồ Điệp Phú Quý',
      slug: 'chau-lan-ho-diep-phu-quy',
      description: 'Chậu 3 cành lan hồ điệp trắng sang trọng, phù hợp biếu tặng',
      price: 1200000,
      category: 'arrangement' as const,
      flowerComposition: [{ flowerId: flowerMap['hoa-lan-ho-diep'], quantity: 3 }],
      images: [img('chau-lan-ho-diep', 1, true)],
      customizationOptions: [
        { name: 'Chậu', options: [{ label: 'Sứ trắng', priceModifier: 0 }, { label: 'Gốm men', priceModifier: 80000 }] },
      ],
      occasions: ['tet', 'birthday', 'custom'],
      emotions: ['respectful', 'celebratory'],
      stock: { quantity: 15, unlimited: false },
      isAvailable: true,
      totalSold: 42,
      averageRating: 4.9,
      tags: ['lan hồ điệp', 'sang trọng', 'tết', 'biếu tặng'],
    },
    {
      shopId: shopMap['hoa-sai-gon'],
      flowerId: flowerMap['hoa-sen'],
      name: 'Bó Sen Hồng Thanh Khiết',
      slug: 'bo-sen-hong-thanh-khiet',
      description: 'Bó 10 sen hồng mùa hè, đại diện sự thuần khiết và thanh cao',
      price: 250000,
      category: 'bouquet' as const,
      flowerComposition: [{ flowerId: flowerMap['hoa-sen'], quantity: 10 }],
      images: [img('bo-sen-hong', 1, true)],
      customizationOptions: [],
      occasions: ['custom', 'birthday'],
      emotions: ['respectful', 'grateful'],
      stock: { quantity: 20, unlimited: false },
      isAvailable: true,
      totalSold: 67,
      averageRating: 4.6,
      tags: ['sen', 'thanh khiết', 'Việt Nam'],
    },
    {
      shopId: shopMap['hoa-sai-gon'],
      name: 'Hộp Hoa Mix Pastel',
      slug: 'hop-hoa-mix-pastel',
      description: 'Hộp hoa phối pastel gồm hồng phấn, cẩm tú cầu, cát tường',
      price: 550000,
      category: 'box' as const,
      flowerComposition: [
        { flowerId: flowerMap['hoa-hong-phan'], quantity: 5 },
        { flowerId: flowerMap['hoa-cam-tu-cau'], quantity: 3 },
        { flowerId: flowerMap['hoa-cat-tuong'], quantity: 4 },
      ],
      images: [img('hop-mix-pastel', 1, true), img('hop-mix-pastel', 2)],
      customizationOptions: [
        { name: 'Kích thước', options: [{ label: 'Vừa', priceModifier: 0 }, { label: 'Lớn', priceModifier: 150000 }] },
      ],
      occasions: ['birthday', 'anniversary', 'womens_day'],
      emotions: ['romantic', 'joyful', 'grateful'],
      stock: { quantity: 25, unlimited: false },
      isAvailable: true,
      totalSold: 93,
      averageRating: 4.8,
      tags: ['hộp hoa', 'pastel', 'mix hoa'],
    },

    // === Hoa Đà Lạt (5 products) ===
    {
      shopId: shopMap['hoa-da-lat'],
      flowerId: flowerMap['hoa-cam-tu-cau'],
      name: 'Bó Cẩm Tú Cầu Đà Lạt',
      slug: 'bo-cam-tu-cau-da-lat',
      description: 'Bó cẩm tú cầu xanh tím đặc trưng Đà Lạt, tươi lâu 7-10 ngày',
      price: 320000,
      category: 'bouquet' as const,
      flowerComposition: [{ flowerId: flowerMap['hoa-cam-tu-cau'], quantity: 5 }],
      images: [img('bo-cam-tu-cau', 1, true)],
      customizationOptions: [
        { name: 'Màu', options: [{ label: 'Xanh', priceModifier: 0 }, { label: 'Tím', priceModifier: 20000 }] },
      ],
      occasions: ['birthday', 'anniversary', 'custom'],
      emotions: ['romantic', 'grateful'],
      stock: { quantity: 40, unlimited: false },
      isAvailable: true,
      totalSold: 156,
      averageRating: 4.8,
      tags: ['cẩm tú cầu', 'Đà Lạt', 'tươi lâu'],
    },
    {
      shopId: shopMap['hoa-da-lat'],
      flowerId: flowerMap['hoa-lavender'],
      name: 'Bó Lavender Khô Thơm',
      slug: 'bo-lavender-kho-thom',
      description: 'Bó lavender sấy khô tự nhiên từ Đà Lạt, giữ hương 6 tháng',
      price: 180000,
      category: 'bouquet' as const,
      flowerComposition: [{ flowerId: flowerMap['hoa-lavender'], quantity: 15 }],
      images: [img('bo-lavender-kho', 1, true)],
      customizationOptions: [],
      occasions: ['birthday', 'custom'],
      emotions: ['friendly', 'grateful'],
      stock: { quantity: 0, unlimited: true },
      isAvailable: true,
      totalSold: 234,
      averageRating: 4.4,
      tags: ['lavender', 'hoa khô', 'Đà Lạt', 'thơm'],
    },
    {
      shopId: shopMap['hoa-da-lat'],
      flowerId: flowerMap['hoa-tulip'],
      name: 'Hộp Tulip Hà Lan',
      slug: 'hop-tulip-ha-lan',
      description: 'Hộp 15 tulip nhập Hà Lan nhiều màu, bảo quản lạnh',
      price: 750000,
      category: 'box' as const,
      flowerComposition: [{ flowerId: flowerMap['hoa-tulip'], quantity: 15 }],
      images: [img('hop-tulip', 1, true), img('hop-tulip', 2)],
      customizationOptions: [
        { name: 'Màu', options: [{ label: 'Mix', priceModifier: 0 }, { label: 'Đỏ', priceModifier: 0 }, { label: 'Hồng', priceModifier: 0 }] },
      ],
      occasions: ['valentines', 'birthday', 'womens_day'],
      emotions: ['romantic', 'joyful'],
      stock: { quantity: 10, unlimited: false },
      isAvailable: true,
      totalSold: 38,
      averageRating: 4.9,
      tags: ['tulip', 'nhập khẩu', 'Hà Lan', 'cao cấp'],
    },
    {
      shopId: shopMap['hoa-da-lat'],
      flowerId: flowerMap['hoa-da-yen-thao'],
      name: 'Chậu Dạ Yến Thảo Rực Rỡ',
      slug: 'chau-da-yen-thao-ruc-ro',
      description: 'Chậu dạ yến thảo mix 3 màu, nở quanh năm tại Đà Lạt',
      price: 150000,
      category: 'arrangement' as const,
      flowerComposition: [{ flowerId: flowerMap['hoa-da-yen-thao'], quantity: 1 }],
      images: [img('chau-da-yen-thao', 1, true)],
      customizationOptions: [],
      occasions: ['custom', 'birthday'],
      emotions: ['joyful', 'friendly'],
      stock: { quantity: 60, unlimited: false },
      isAvailable: true,
      totalSold: 112,
      averageRating: 4.3,
      tags: ['dạ yến thảo', 'chậu hoa', 'Đà Lạt'],
    },
    {
      shopId: shopMap['hoa-da-lat'],
      name: 'Bó Hoa Cưới Đà Lạt',
      slug: 'bo-hoa-cuoi-da-lat',
      description: 'Bó hoa cưới cầm tay phối hồng trắng, cát tường và baby',
      price: 650000,
      category: 'bouquet' as const,
      flowerComposition: [
        { flowerId: flowerMap['hoa-hong-trang'], quantity: 10 },
        { flowerId: flowerMap['hoa-cat-tuong'], quantity: 5 },
        { flowerId: flowerMap['hoa-baby'], quantity: 8 },
      ],
      images: [img('bo-hoa-cuoi', 1, true)],
      customizationOptions: [],
      occasions: ['wedding'],
      emotions: ['romantic', 'joyful'],
      stock: { quantity: 10, unlimited: false },
      isAvailable: true,
      totalSold: 27,
      averageRating: 5.0,
      tags: ['hoa cưới', 'cầm tay', 'Đà Lạt'],
    },

    // === Hoa Thủ Đô - Hà Nội (5 products) ===
    {
      shopId: shopMap['hoa-thu-do'],
      flowerId: flowerMap['hoa-ly'],
      name: 'Bó Ly Trắng Thanh Lịch',
      slug: 'bo-ly-trang-thanh-lich',
      description: 'Bó 10 hoa ly trắng thơm ngát, biểu tượng sự thanh cao',
      price: 350000,
      category: 'bouquet' as const,
      flowerComposition: [{ flowerId: flowerMap['hoa-ly'], quantity: 10 }],
      images: [img('bo-ly-trang', 1, true)],
      customizationOptions: [],
      occasions: ['birthday', 'custom', 'funeral'],
      emotions: ['respectful', 'sympathetic'],
      stock: { quantity: 25, unlimited: false },
      isAvailable: true,
      totalSold: 74,
      averageRating: 4.6,
      tags: ['hoa ly', 'trắng', 'thanh lịch'],
    },
    {
      shopId: shopMap['hoa-thu-do'],
      flowerId: flowerMap['hoa-dao'],
      name: 'Cành Đào Tết Thắm',
      slug: 'canh-dao-tet-tham',
      description: 'Cành đào phai Nhật Tân, hoa nở đúng Tết',
      price: 500000,
      salePrice: 400000,
      category: 'single_flower' as const,
      flowerComposition: [{ flowerId: flowerMap['hoa-dao'], quantity: 1 }],
      images: [img('canh-dao-tet', 1, true)],
      customizationOptions: [],
      occasions: ['tet'],
      emotions: ['celebratory', 'joyful'],
      stock: { quantity: 0, unlimited: false },
      isAvailable: false,
      totalSold: 200,
      averageRating: 4.7,
      tags: ['đào', 'tết', 'Nhật Tân', 'Hà Nội'],
    },
    {
      shopId: shopMap['hoa-thu-do'],
      flowerId: flowerMap['hoa-cuc'],
      name: 'Lẵng Cúc Vàng Khai Trương',
      slug: 'lang-cuc-vang-khai-truong',
      description: 'Lẵng hoa cúc vàng lớn kèm ruy-băng chúc mừng khai trương',
      price: 800000,
      category: 'basket' as const,
      flowerComposition: [
        { flowerId: flowerMap['hoa-cuc'], quantity: 20 },
        { flowerId: flowerMap['hoa-dong-tien'], quantity: 10 },
      ],
      images: [img('lang-cuc-vang', 1, true)],
      customizationOptions: [
        { name: 'Ruy-băng', options: [{ label: 'Chúc mừng', priceModifier: 0 }, { label: 'Tuỳ chỉnh', priceModifier: 50000 }] },
      ],
      occasions: ['custom', 'graduation'],
      emotions: ['celebratory', 'joyful'],
      stock: { quantity: 0, unlimited: true },
      isAvailable: true,
      totalSold: 45,
      averageRating: 4.5,
      tags: ['khai trương', 'cúc vàng', 'lẵng hoa'],
    },
    {
      shopId: shopMap['hoa-thu-do'],
      name: 'Bó Hoa Mix 8/3',
      slug: 'bo-hoa-mix-8-3',
      description: 'Bó hoa phối hồng phấn, cẩm chướng và cát tường cho ngày 8/3',
      price: 280000,
      category: 'bouquet' as const,
      flowerComposition: [
        { flowerId: flowerMap['hoa-hong-phan'], quantity: 5 },
        { flowerId: flowerMap['hoa-cam-chuong'], quantity: 5 },
        { flowerId: flowerMap['hoa-cat-tuong'], quantity: 3 },
      ],
      images: [img('bo-mix-8-3', 1, true)],
      customizationOptions: [],
      occasions: ['womens_day', 'mothers_day', 'birthday'],
      emotions: ['grateful', 'romantic'],
      stock: { quantity: 40, unlimited: false },
      isAvailable: true,
      totalSold: 180,
      averageRating: 4.4,
      tags: ['8/3', 'phụ nữ', 'hoa mix'],
    },
    {
      shopId: shopMap['hoa-thu-do'],
      flowerId: flowerMap['hoa-hong-vang'],
      name: 'Bó Hồng Vàng Tri Ân',
      slug: 'bo-hong-vang-tri-an',
      description: 'Bó 12 hồng vàng phối lá bạc, thích hợp tri ân thầy cô',
      price: 320000,
      category: 'bouquet' as const,
      flowerComposition: [{ flowerId: flowerMap['hoa-hong-vang'], quantity: 12 }],
      images: [img('bo-hong-vang', 1, true)],
      customizationOptions: [],
      occasions: ['custom', 'graduation'],
      emotions: ['grateful', 'respectful'],
      stock: { quantity: 30, unlimited: false },
      isAvailable: true,
      totalSold: 56,
      averageRating: 4.5,
      tags: ['hồng vàng', 'tri ân', 'thầy cô'],
    },

    // === Hoa Biển Đà Nẵng (5 products) ===
    {
      shopId: shopMap['hoa-bien-da-nang'],
      flowerId: flowerMap['hoa-thien-dieu'],
      name: 'Bó Thiên Điểu Nhiệt Đới',
      slug: 'bo-thien-dieu-nhiet-doi',
      description: 'Bó 5 thiên điểu cam rực rỡ phong cách tropical',
      price: 420000,
      category: 'bouquet' as const,
      flowerComposition: [{ flowerId: flowerMap['hoa-thien-dieu'], quantity: 5 }],
      images: [img('bo-thien-dieu', 1, true)],
      customizationOptions: [],
      occasions: ['birthday', 'custom'],
      emotions: ['joyful', 'celebratory'],
      stock: { quantity: 20, unlimited: false },
      isAvailable: true,
      totalSold: 33,
      averageRating: 4.6,
      tags: ['thiên điểu', 'tropical', 'Đà Nẵng'],
    },
    {
      shopId: shopMap['hoa-bien-da-nang'],
      flowerId: flowerMap['hoa-hong-do'],
      name: 'Giỏ Hoa Tình Yêu Biển',
      slug: 'gio-hoa-tinh-yeu-bien',
      description: 'Giỏ mây phối hồng đỏ, baby và lá dương xỉ phong cách biển',
      price: 480000,
      category: 'basket' as const,
      flowerComposition: [
        { flowerId: flowerMap['hoa-hong-do'], quantity: 10 },
        { flowerId: flowerMap['hoa-baby'], quantity: 5 },
      ],
      images: [img('gio-tinh-yeu-bien', 1, true)],
      customizationOptions: [],
      occasions: ['valentines', 'anniversary'],
      emotions: ['romantic', 'passionate'],
      stock: { quantity: 15, unlimited: false },
      isAvailable: true,
      totalSold: 48,
      averageRating: 4.7,
      tags: ['giỏ mây', 'biển', 'tình yêu'],
    },
    {
      shopId: shopMap['hoa-bien-da-nang'],
      flowerId: flowerMap['hoa-dong-tien'],
      name: 'Bó Đồng Tiền Sắc Màu',
      slug: 'bo-dong-tien-sac-mau',
      description: 'Bó 15 đồng tiền đa sắc, mang ý nghĩa may mắn và thành công',
      price: 200000,
      category: 'bouquet' as const,
      flowerComposition: [{ flowerId: flowerMap['hoa-dong-tien'], quantity: 15 }],
      images: [img('bo-dong-tien', 1, true)],
      customizationOptions: [],
      occasions: ['birthday', 'get_well', 'custom'],
      emotions: ['joyful', 'friendly'],
      stock: { quantity: 0, unlimited: true },
      isAvailable: true,
      totalSold: 92,
      averageRating: 4.3,
      tags: ['đồng tiền', 'may mắn', 'sắc màu'],
    },
    {
      shopId: shopMap['hoa-bien-da-nang'],
      name: 'Hộp Hoa Sang Trọng Premium',
      slug: 'hop-hoa-sang-trong-premium',
      description: 'Hộp gỗ phối hoa hồng, mẫu đơn và cát tường phong cách luxury',
      price: 950000,
      category: 'box' as const,
      flowerComposition: [
        { flowerId: flowerMap['hoa-hong-phan'], quantity: 8 },
        { flowerId: flowerMap['hoa-mau-don'], quantity: 3 },
        { flowerId: flowerMap['hoa-cat-tuong'], quantity: 5 },
      ],
      images: [img('hop-sang-trong', 1, true), img('hop-sang-trong', 2)],
      customizationOptions: [
        { name: 'Nến thơm', options: [{ label: 'Không', priceModifier: 0 }, { label: 'Có', priceModifier: 120000 }] },
      ],
      occasions: ['anniversary', 'birthday', 'valentines'],
      emotions: ['romantic', 'grateful'],
      stock: { quantity: 8, unlimited: false },
      isAvailable: true,
      totalSold: 21,
      averageRating: 5.0,
      tags: ['premium', 'luxury', 'hộp gỗ'],
    },
    {
      shopId: shopMap['hoa-bien-da-nang'],
      flowerId: flowerMap['hoa-mimosa'],
      name: 'Bó Mimosa Nắng Vàng',
      slug: 'bo-mimosa-nang-vang',
      description: 'Bó mimosa vàng tươi, biểu tượng của sự nhạy cảm và dịu dàng',
      price: 220000,
      category: 'bouquet' as const,
      flowerComposition: [{ flowerId: flowerMap['hoa-mimosa'], quantity: 10 }],
      images: [img('bo-mimosa', 1, true)],
      customizationOptions: [],
      occasions: ['womens_day', 'birthday'],
      emotions: ['friendly', 'grateful'],
      stock: { quantity: 25, unlimited: false },
      isAvailable: true,
      totalSold: 44,
      averageRating: 4.5,
      tags: ['mimosa', 'vàng', 'dịu dàng'],
    },

  ];
}
